### ISSUE TITLE
TiKV panic repeatedly: [FATAL] [lib.rs:465] ["unstable.slice[22, 23] out of bound[22, 22], raft_id: 115835, region_id: 115832"]

### ISSUE THREAD

**Issue by Tammyxia** [tikv/tikv#13554] opened 2022-09-28 09:39 UTC
### What version of TiKV are you using?

TiKV
Release Version:   5.4.1
Edition:           Community
Git Commit Hash:   91fe561f0af87cc47359cdf61d6e6838471cb644
Git Commit Branch: heads/refs/tags/v5.4.1
UTC Build Time:    2022-05-13 02:34:08
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

### Steps to reproduce

- Create TiDB cluster v5.4.1 on AWS EKS by operator, 3 TiKV node.
- Run sysbench oltp_common prepare
- Run sysbench oltp_insert run

### What did you expect?
No any error.

### What did happened?

- TiKV-0 and TiKV-1 OOM, known issue
- Then TiKV-1 recovered, but TiKV-0 panic repeatedly, tikv.log::
[2022/09/28 08:58:13.426 +00:00] [FATAL] [lib.rs:465] ["unstable.slice[22, 23] out of bound[22, 22], raft_id: 115835, region_id: 115832"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:464:18\n   1: std::panicking::rust_panic_with_hook\n             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panicking.rs:626:17\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panicking.rs:519:13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/sys_common/backtrace.rs:141:18\n   4: rust_begin_unwind\n             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panicking.rs:515:5\n   5: std::panicking::begin_panic_fmt\n             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panicking.rs:457:5\n   6: raft::log_unstable::Unstable::must_check_outofbounds\n             at rust/git/checkouts/raft-rs-42b8049ef2e3af07/e6d28ef/src/log_unstable.rs:204:13\n   7: raft::log_unstable::Unstable::truncate_and_append\n             at rust/git/checkouts/raft-rs-42b8049ef2e3af07/e6d28ef/src/log_unstable.rs:169:13\n   8: raft::raft_log::RaftLog<T>::append\n             at rust/git/checkouts/raft-rs-42b8049ef2e3af07/e6d28ef/src/raft_log.rs:377:9\n   9: raft::raft_log::RaftLog<T>::maybe_append\n             at rust/git/checkouts/raft-rs-42b8049ef2e3af07/e6d28ef/src/raft_log.rs:268:17\n  10: raftstore::store::peer::Peer<EK,ER>::maybe_append_merge_entries\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/peer.rs:845:9\n      raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_catch_up_logs_for_merge\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:3284:15\n      raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_significant_msg\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:1132:17\n      raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::handle_msgs\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:615:49\n  11: <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_normal\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:797:9\n  12: batch_system::batch::Poller<N,C,Handler>::poll\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:406:27\n  13: raftstore::store::worker::refresh_config::PoolController<N,C,H>::increase_by::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/worker/refresh_config.rs:71:21\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/sys_common/backtrace.rs:125:18\n  14: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}\n             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/thread/mod.rs:476:17\n      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panic.rs:347:9\n      std::panicking::try::do_call\n             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panicking.rs:401:40\n      std::panicking::try\n             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panicking.rs:365:19\n      std::panic::catch_unwind\n             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panic.rs:434:14\n      std::thread::Builder::spawn_unchecked::{{closure}}\n             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/thread/mod.rs:475:30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/ops/function.rs:227:5\n  15: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/alloc/src/boxed.rs:1572:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/alloc/src/boxed.rs:1572:9\n      std::sys::unix::thread::Thread::new::thread_start\n             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/sys/unix/thread.rs:91:17\n  16: <unknown>\n  17: clone\n"] [location=/rust/git/checkouts/raft-rs-42b8049ef2e3af07/e6d28ef/src/log_unstable.rs:204] [thread_name=raftstore-5-3]

**Comment by AndreMouche** [comment] 2023-10-09 07:20
Friendly ping, same issue in v6.5.4 when start tikv:
```
["unstable.slice[28051, 28055] out of bound[28051, 28051], raft_id: 2010234007, region_id: 2010234004"] 
[backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             
at tikv/components/tikv_util/src/lib.rs:508:18\n   
1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\n    
 at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2032:9\n      std::panicking::rust_panic_with_hook\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:692:13\n   
 2: std::panicking::begin_panic_handler::{{closure}}\n            
  at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:579:13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137:18\n   
  4: rust_begin_unwind\n             
  at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:575:5\n   5: core::panicking::panic_fmt\n            
   at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:65:14\n  
    6: raft::log_unstable::Unstable::must_check_outofbounds\n           
at root/.cargo/git/checkouts/raft-rs-42b8049ef2e3af07/2357cb2/src/log_unstable.rs:201:13\n  
 7: raft::log_unstable::Unstable::truncate_and_append\n    
at root/.cargo/git/checkouts/raft-rs-42b8049ef2e3af07/2357cb2/src/log_unstable.rs:169:13\n 
  8: raft::raft_log::RaftLog<T>::append\n        
at root/.cargo/git/checkouts/raft-rs-42b8049ef2e3af07/2357cb2/src/raft_log.rs:377:9\n  
 9: raft::raft_log::RaftLog<T>::maybe_append\n            
  at root/.cargo/git/checkouts/raft-rs-42b8049ef2e3af07/2357cb2/src/raft_log.rs:268:17\n 
   10: raftstore::store::peer::Peer<EK,ER>::maybe_append_merge_entries\n           
     at tikv/components/raftstore/src/store/peer.rs:1369:9\n     
      raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_catch_up_logs_for_merge\n             at tikv/components/raftstore/src/store/fsm/peer.rs:4466:15\n      raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_significant_msg\n             at tikv/components/raftstore/src/store/fsm/peer.rs:1403:17\n  11: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::handle_msgs\n             at tikv/components/raftstore/src/store/fsm/peer.rs:666:49\n  12: <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_normal\n             at tikv/components/raftstore/src/store/fsm/store.rs:971:9\n  13: batch_system::batch::Poller<N,C,Handler>::poll\n             at tikv/components/batch-system/src/batch.rs:430:27\n  14: batch_system::batch::BatchSystem<N,C>::start_poller::{{closure}}\n             at tikv/components/batch-system/src/batch.rs:600:17\n      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}\n             at tikv/components/tikv_util/src/sys/thread.rs:415:23\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:121:18\n  15: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:551:17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:271:9\n      std::panicking::try::do_call\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:483:40\n      std::panicking::try\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:447:19\n      std::panic::catch_unwind\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:550:30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:513:5\n  16: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9\n      std::sys::unix::thread::Thread::new::thread_start\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17\n  17: start_thread\n  18: __clone3\n"] [location=/root/.cargo/git/checkouts/raft-rs-42b8049ef2e3af07/2357cb2/src/log_unstable.rs:201] 
[thread_name=raftstore-1942158-0]
```
It seems that the case of entry being empty was not considered during initialization.


https://github.com/tikv/raft-rs/blob/10c6e9db6792b85c81784e44fc278f895d5f0ab0/src/log_unstable.rs#L156-L177

https://github.com/tikv/raft-rs/blob/10c6e9db6792b85c81784e44fc278f895d5f0ab0/src/log_unstable.rs#L195-L211

**Comment by overvenus** [comment] 2023-10-10 02:23
The panic is caused by ebs backup breaks region merge assumption: when proposing commit merge, all source peers must have raft logs that is large than or equal to prepare merge min index. But in ebs backup, the snapshot of panic tikv is taken before merge (does not have enough raft logs), and the snapshot of other tikvs is taken after merge. So the target region leader sends CommitMerge raft log to panic tikv, but the source region leader doesn't send the following raft log (because it is merged), which causes the source region to panic when handling CatchUpLogs from target region.

**Comment by BornChanger** [comment] 2023-11-06 15:02
@tonyxuqqi It seems this issue has nothing to do with br.

**Comment by BornChanger** [comment] 2024-04-02 01:47
br panic issue has been fixed by https://github.com/tikv/tikv/pull/15946

**Closed** 2024-05-22 08:41 UTC
Labels: type/bug, severity/major, affects-6.1, affects-6.5, affects-7.1, affects-7.5, affects-8.1
