### ISSUE TITLE
how to make a Fuzzy Query?

### ISSUE THREAD

**Issue by itcheng2019** [tikv/tikv#5047] opened 2019-07-09 02:40 UTC
sometime i want to query same key has prefix,  just like mysql :select * from ATable  where name like "prefix%"

**Comment by disksing** [comment] 2019-07-09 10:14
Hi @itcheng2019 , do you use TiKV along with `tidb-server`, or use the `txnkv API`, or use the `rawkv API`?
- If you use tidb, you can use the mysql compatible like syntax.
- If you use txnKV or rawKV, you can use `Scan` functions to iterate all keys with the same prefix.

**Comment by itcheng2019** [comment] 2019-07-09 10:21
@disksing 
i use the txnkv API 
the Scan function work no good. if you scan a key begin with Symbol char ,it will scan all keys

**Comment by disksing** [comment] 2019-07-09 12:15
You can specify an `upperBound` when creating the iterator. The bound key can be determined using [PrefixNext](https://github.com/pingcap/tidb/blob/bd4130d1f34944691126c29d7d72246ca5cbd36c/kv/key.go#L29-L55) method. For example, to scan keys start with `prefix`, you can set start key as `prefix` and upper bound as `prefiy`.

**Comment by itcheng2019** [comment] 2019-07-09 12:18
@disksing
the result of this opt is empty

**Comment by itcheng2019** [comment] 2019-07-09 12:19
and Scan function will get somekey deleted

**Comment by disksing** [comment] 2019-07-09 12:55
scan is a readonly command, it won't do delete. Could you provide detailed steps to reproduce this problem?

**Comment by itcheng2019** [comment] 2019-07-10 01:22
@disksing
i used the delete function to delete a key.after, use get function to get a key deleted will return a err that key not exits. use scan function will get the key and it's value is empty.

steps:
1. put some key like "/abc/def1", "/abc/def2", "/abc/def2","key1","key2"
2. scan a key with prefix "/abc"
3.return all key puted, not key with prefix

**Comment by disksing** [comment] 2019-07-10 10:54
Hi @itcheng2019 It is a client-go bug, I'm fixing it.

**Comment by itcheng2019** [comment] 2019-07-12 01:25
@disksing 
i used tikv first time , maybe i hava a wrong operation. please do again, and tell me.

**Comment by disksing** [comment] 2019-07-12 07:30
It's fixed in master now. Please check latest master branch.

**Comment by itcheng2019** [comment] 2019-07-12 07:36
> 
> 
> It's fixed in master now. Please check latest master branch.

ok, thank you very much

**Comment by itcheng2019** [comment] 2019-07-16 01:33
hi， @disksing 
the same problem


====================put=========================
func main() {
	pdAddr := os.Getenv("PD_ADDR")
	if pdAddr != "" {
		os.Args = append(os.Args, "-pd", pdAddr)
	}
	flag.Parse()
	initStore()

	// set , 
	err := puts(
		[]byte("key1"), []byte("value1"),
		[]byte("key2"), []byte("value2"),
		[]byte("/key1"), []byte("value1"),
		[]byte("/key2"), []byte("value2"),
		[]byte("/key1/abc"), []byte("value1"),
		[]byte("/key2/def"), []byte("value2"),
		[]byte("/key1/abc/abc"), []byte("value1"),
		[]byte("/key2/def/def"), []byte("value2"))
	if err != nil {
		panic(err)
	}
	fmt.Println("put ok")
}

====================scan=========================
func scan(keyPrefix []byte, limit int) ([]KV, error) {
	tx, err := client.Begin(context.TODO())
	if err != nil {
		return nil, err
	}
	it, err := tx.Iter(context.TODO(), key.Key(keyPrefix), nil)
	if err != nil {
		return nil, err
	}
	defer it.Close()
	var ret []KV
	for it.Valid() && limit > 0 {
		ret = append(ret, KV{K: it.Key()[:], V: it.Value()[:]})
		limit--
		it.Next(context.TODO())
	}
	return ret, nil
}

func main() {
	pdAddr := os.Getenv("PD_ADDR")
	if pdAddr != "" {
		os.Args = append(os.Args, "-pd", pdAddr)
	}
	flag.Parse()
	initStore()

	// scan
	ret, _ := scan([]byte("**/key**"), 100000)
	for _, kv := range ret {
		fmt.Println(kv)
	}
}
===============================
the result is it get all key

if 
	it, err := tx.Iter(context.TODO(), key.Key(keyPrefix), key.Key(keyPrefix))
will get none

**Comment by disksing** [comment] 2019-07-16 03:29
Hi @itcheng2019 , we do not support wildcard now. `scan("**/key**")` returns all keys because "*" is less than "k" and "/" in ASCII order. ` tx.Iter(context.TODO(), key.Key(keyPrefix), key.Key(keyPrefix))` returns none because the second key is the upperbound of the iterator.

**Comment by itcheng2019** [comment] 2019-07-16 06:29
> 
> 
> Hi @itcheng2019 , we do not support wildcard now. `scan("**/key**")` returns all keys because "*" is less than "k" and "/" in ASCII order. ` tx.Iter(context.TODO(), key.Key(keyPrefix), key.Key(keyPrefix))` returns none because the second key is the upperbound of the iterator.

sorry, the keyPrefix is "/key",not "**/key**"

func main() {
	pdAddr := os.Getenv("PD_ADDR")
	if pdAddr != "" {
		os.Args = append(os.Args, "-pd", pdAddr)
	}
	flag.Parse()
	initStore()

	// scan
	ret, _ := scan([]byte("/key"), 100000)
	for _, kv := range ret {
		fmt.Println(kv)
	}
}

**Comment by disksing** [comment] 2019-07-16 08:31
@itcheng2019 Please note that it is totally reasonable to return all keys, because in ASCII order, "/" is before "k". You can see, all keys are greater than the start key.
To iterator all keys starts with "/key", you can try `tx.Iter(ctx, "/key", "/kez")`.

**Comment by itcheng2019** [comment] 2019-07-16 12:22
> 
> 
> @itcheng2019 Please note that it is totally reasonable to return all keys, because in ASCII order, "/" is before "k". You can see, all keys are greater than the start key.
> To iterator all keys starts with "/key", you can try `tx.Iter(ctx, "/key", "/kez")`.

ok，thanks!

**Closed** 2019-07-17 02:09 UTC
Labels: C: TiKV-Client, T: Question
