### ISSUE TITLE
Fix Failing pipeline - tikv_ghpr_integration_common_test

### ISSUE THREAD

**Issue by karuppiah7890** [tikv/tikv#10850] opened 2021-08-28 15:04 UTC
## Development Task

A lot of the commits in this repo's `master` have a red status https://github.com/tikv/tikv/commits/master and I noticed many of them are failing only in area - `idc-jenkins-ci-tikv/integration-common-test`, which points to a Jenkins pipeline with the name `tikv_ghpr_integration_common_test` in it

At the time of this writing, the latest failure is https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_integration_common_test/detail/tikv_ghpr_integration_common_test/2928/pipeline from this commit - https://github.com/tikv/tikv/commit/2934196762268d6b1a664d1cbce9b24769e33f20

I think it's important to avoid red status commits and failing pipelines, as those are indicative of some issue and need to be looked at - if it's a bug / actual failure, fix it, or else if it's flaky, deflake it.

I recently noticed etcd repo taking an interesting approach in case of flaky tests - https://github.com/etcd-io/etcd/issues/13167 , it inspired me to checkout further more about tests specifically failing ones and flaky ones, which I usually try to debug and fix

I'm not sure if it's flaky or not or what's going on in this case, since I haven't debugged / dug deeper. Maybe digging deeper might help, I'll see if I can check more on this sometime when I can

**Comment by tisonkun** [comment] 2021-08-29 11:12
Thanks for your reporting @karuppiah7890 !

Agree it's significant to ensure ci stability. @BusyJay @skyzh @zhouqiang-cl do you have ideas on tikv_ghpr_integration_common_test failures?

**Comment by skyzh** [comment] 2021-08-29 11:23
Commits on master should be running the same continuous integration procedure as pull requests. It’s weird that PRs pass the tests, but when they come to master branch, they fail…

**Comment by tisonkun** [comment] 2021-08-29 11:26
@skyzh no. I think we're now running only building and unit tests for pull requests.

**Comment by skyzh** [comment] 2021-08-29 11:28
Only maintainers and committers could trigger integration tests by `/merge` or `/run-all-tests`. Integration tests won’t run by default.

**Comment by skyzh** [comment] 2021-08-29 11:29
Just find out that integration test is not running in PRs… Something has changed 😂

**Comment by skyzh** [comment] 2021-08-29 11:32
I guess https://github.com/pingcap/tidb/pull/27484 is the root cause of failure. By the way, why is integration-test not running in PRs?????

**Comment by tisonkun** [comment] 2021-08-29 12:51
> ~Only maintainers and committers could trigger integration tests by `/merge` or `/run-all-tests`. Integration tests won’t run by default.~

IIRC you can still trigger integration tests by `/run-integretion-tests` or something. I'm driving our infra team member to post an announcement on internals.tidb.io and it may include the information or at least we can ask for it.

@purelind I remember you summarize our ci pipeline and commands communicate with them. In our previous discussion we'd like to tight them up with the repo. Is there any progress? We can create an issue to trace the document writing task.

**Comment by skyzh** [comment] 2021-08-29 13:19
I believe `run-integretion-tests` is a must especially for copr-related PRs. Otherwise our contributors will never know if they siliently break anything.

**Comment by purelind** [comment] 2021-08-30 01:40
@tisonkun  Docs on ci pipeline and trigger phrases to communicate with them are on progress。An issue to trace the docs writting task will be much better.

**Comment by BusyJay** [comment] 2021-08-30 05:05
@zhouqiang-cl can you take a look? I remember the case is taken down for CI speed. We assumed some one will watch master's status and fix potential problems. Though it seems to be contrary.

**Comment by tisonkun** [comment] 2021-08-31 16:22
closed as master CI fixed. @zhouqiang-cl spotted that it is caused by https://github.com/pingcap/tidb/issues/27673 .

But we can still think of turning on copr related tests for PRs, moving to https://github.com/tikv/tikv/issues/10877 FYI.

**Closed by tisonkun** 2021-08-31 16:22 UTC
Labels: type/enhancement, component/test
