### ISSUE TITLE
Insert data into single table， after running for a period of time, large region are generated

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#10762] opened 2021-08-17 12:37 UTC
### What version of TiKV are you using?
TiKV
Release Version: 5.1.0-alpha
Edition: Community
Git Commit Hash: f67aa380277b333a5b879f7837af51a9bd4ee0b8
Git Commit Branch: slow-store-fix-5.2
UTC Build Time: 2021-08-06 06:39:43
Rust Version: rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features: jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile: release

### What operating system and CPU are you using?
tiup ：
1PD
1TiDB
3TiKV
all node：500G NVME、4 cores、8G mem

### Steps to reproduce
1、sysbench --config-file=/root/config oltp_point_select --tables=1 --table-size=10000000000 --auto_inc=true prepare
threads=1

### What did you expect?
do not generate barge region

### What did happened?
after running for a period of time, large region are generated within a period of time
![Lark20210817-203631](https://user-images.githubusercontent.com/84712107/129726681-1dcde593-2fbe-4c7f-ba33-e6fd2253cdd5.png)

**Comment by BusyJay** [comment] 2021-08-17 12:55
@hicqu can you take a look to check if it's a fixed issue?

**Comment by hicqu** [comment] 2021-08-18 12:26
There is a bug about calculating approximate keys and size for a region:
```
[2021/08/17 19:01:15.927 +08:00] [INFO] [size.rs:168] ["approximate size over threshold, need to do split check"] [threshold=150994944] [size=907068400] [region_id=54685]
[2021/08/17 19:01:15.928 +08:00] [INFO] [keys.rs:154] ["approximate keys over threshold, need to do split check"] [threshold=1440000] [keys=3702320] [region_id=54685]
[2021/08/17 19:01:23.157 +08:00] [INFO] [split_check.rs:289] ["update approximate size and keys with accurate value"] [keys=0] [size=0] [region_id=54685]
[2021/08/17 19:02:11.186 +08:00] [INFO] [pd.rs:1146] ["try to merge"] [merge="target { id: 55377 start_key: 7480000000000004FF0B00000000000000F8 end_key: 7480000000000004FF0F00000000000000F8 region_epoch { conf_ver: 5 version: 5782 } peers { id: 55378 store_id: 1 } peers { id: 55379 store_id: 5 } peers { id: 55380 store_id: 4 } }"] [region_id=54685]
```

I will fix it later.

**Comment by hicqu** [comment] 2021-08-25 10:05
The PR #10776 is trying to fix a unexist problem. I will close it.
So back to the issue, seems it can only be the range is cleaned by `delete_files_in_range` after `add_checker` checks.

**Comment by hicqu** [comment] 2021-11-23 05:23
The issue contains 2 questions:
1. why region size jumps between 0 and a large value;
2. why large region (size about 1.8GB) occurs.

The answer to the first question is there are 2 source for a region size:
a. real size of the region by scan, which will be 0.
b. approximate size from table properties, which didn't filter out L0 files.
So region size can jump. It can lead some unnecessary splits, which can be improved.

The answer to the second question is region splitting uses scan policy by default. It will be switched to approximate policy only if region size is larger than 10x region size. It's by design and won't be fixed.

**Closed** 2022-07-12 06:48 UTC
Labels: type/bug, severity/major, affects-6.0, affects-6.1
