### ISSUE TITLE
[Dynamic Regions] latency spike caused by PessimisticLock when running tpcc stability workload with v2

### ISSUE THREAD

**Issue by dbsid** [tikv/tikv#14675] opened 2023-04-29 12:57 UTC
### What version of TiKV are you using?

lastest master with pr https://github.com/tikv/tikv/pull/14536
### What operating system and CPU are you using?

x86
### Steps to reproduce

run tpcc 1k warehouse for 7 days

### What did you expect?
qps and latency is stable.

### What did happened?
qps and latency spikes, caused by PessimisticLock kv request latency spike.

![image](https://user-images.githubusercontent.com/2316425/235303640-d228ea9c-c057-4fb7-aa12-d7a0354996bd.png)
![image](https://user-images.githubusercontent.com/2316425/235303650-3e426d7b-5093-496e-a755-ff44448b434d.png)
![image](https://user-images.githubusercontent.com/2316425/235303663-f16ab8d7-ff3f-4fed-860a-a2950044998a.png)

**Comment by cfzjywxk** [comment] 2023-05-31 06:50
The root cause may be https://github.com/tikv/tikv/issues/14838, this issue could be marked as duplicate and closed after verifying that fix.

**Closed** 2023-06-05 05:51 UTC
Labels: type/bug, severity/critical
