### ISSUE TITLE
Prune duplicated dependency

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#5595] opened 2019-10-09 02:55 UTC
The current dependency tree contains different versions for same crate, like `syn` and `url`. They increase complie time and make binaries bloat. Here is the full list:

```
 "arbitrary 0.1.1",
 "arbitrary 0.2.0",
 "idna 0.1.5",
 "idna 0.2.0",
 "nom 2.2.1",
 "nom 4.2.3",
 "nom 5.0.1",
 "percent-encoding 1.0.1",
 "percent-encoding 2.1.0",
 "procinfo 0.4.2 (git+https://github.com/tikv/procinfo-rs)",
 "procinfo 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "protobuf 2.8.0 (git+https://github.com/nrc/rust-protobuf?branch=v2.8)",
 "protobuf 2.8.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "protobuf-codegen 2.8.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "quote 0.6.13",
 "quote 1.0.2",
 "raft 0.6.0-alpha (registry+https://github.com/rust-lang/crates.io-index)",
 "raft-proto 0.6.0-alpha (git+https://github.com/pingcap/raft-rs)",
 "raft-proto 0.6.0-alpha (registry+https://github.com/rust-lang/crates.io-index)",
 "rand 0.6.5",
 "rand 0.7.2",
 "rand_chacha 0.1.1",
 "rand_chacha 0.2.1",
 "rand_core 0.3.1",
 "rand_core 0.4.2",
 "rand_core 0.5.1",
 "rand_hc 0.1.0",
 "rand_hc 0.2.0",
 "ryu 0.2.8",
 "ryu 1.0.0",
 "scopeguard 0.3.3",
 "scopeguard 1.0.0",
 "static_assertions 0.2.5",
 "static_assertions 0.3.1",
 "strsim 0.8.0",
 "strsim 0.9.2",
 "syn 0.15.44",
 "syn 1.0.5",
 "unicode-xid 0.1.0",
 "unicode-xid 0.2.0",
 "url 1.7.2",
 "url 2.1.0",
 "winapi 0.2.8",
 "winapi 0.3.8",
```

The list above is generated by 

```bash
grep -E "^ \"[a-z_-]+ ([0-9\.]){3,}" Cargo.lock | sort | uniq
```
It would be nice if we can add such check on CI.

#5592 and #5454

**Comment by hk1997** [comment] 2019-10-09 18:41
Hello I'm new to this project and looking to make my first pull request.
Any tips on how I could take this issue and solve it

**Comment by overvenus** [comment] 2019-10-10 05:31
Hi! @hk1997 

The first step is to locate which crate that is directly dependent by TiKV. Eg, the `rand = "0.6.5"`.

```bash
$ find . -name "Cargo.toml" -exec grep "rand = \"" '{}' \; 
rand = "0.6.5"
rand = "0.6.5"
…
```

Then we look into Cargo.lock, and find out `rand = "0.7.2"` is dependent by `tempfile` which in turn is dependent by TiKV.

Since we always prefer upgrade, we can replace `rand = "0.6.5"` by `rand = "0.7"` in all Cargo.toml, and we run `make clippy` to check whether it compiles.

Errors may pop up, but don't worry most of them are the same, and we can always find a solution in their doc.

After that we may find `rand = "0.6.5"` is still in the dependency tree due to other less up-to-date crates, it’s okay we/they are going to upgrade rand sooner or later.

**Comment by hk1997** [comment] 2019-10-10 08:37
@overvenus  Thank for th heads up. 
I will start working on this issue.

**Comment by nrc** [comment] 2019-10-10 20:36
If the crate is replaced, then there will be two entries in the lock file, but that is not a duplicate dependency, e.g.,

```
"protobuf 2.8.0 (git+https://github.com/nrc/rust-protobuf?branch=v2.8)",
 "protobuf 2.8.0 (registry+https://github.com/rust-lang/crates.io-index)"
```

The first is the crate we replace with, the second is the crate which is replaced. Only the first one is built.

I found that quite a few dups are caused by reqwest which uses old deps in the current published version and new deps on master, but there are a lot of other changes on master too and I don't think they will release soon.

Rand is a mess (very annoying). I found it easier to try and just use 0.6 rather than 0.7 because most of the ecosystem has not upgraded. In any case, rand is mostly used for testing, so I think a better strategy is to try and remove it from the non-dev dependencies so that it does not need to be downloaded or built unless we're testing, I'm not sure if that is the case or not at the moment.

**Comment by hk1997** [comment] 2019-10-11 02:08
Hmm, yes it's difficult to prune duplicate dependencies unless underlying core packages upgrade to newer versions. 
Any heads up on how to identify a dependency as non-dev and remove rand from it

**Comment by nrc** [comment] 2019-10-11 02:18
> Any heads up on how to identify a dependency as non-dev and remove rand from it

To check is easy: compare the output from Cargo for a clean build and check that rand is not built for `cargo build`, but is for `cargo test`. If it is included, then I'm not sure how to fix it - it would depend if it is depended on by one of our crates or a dependency.

**Comment by hk1997** [comment] 2019-10-11 04:53
Did cargo built, rand is being built for cargo build

**Comment by nrc** [comment] 2019-10-14 00:38
I think the next step is to look at Cargo.lock and the individual Cargo.tomls, and find where something uses it as a non-dev dependency. The next step will depend on which crate brings it in. (Note that if a dev-dep uses rand as a non-dev dep, then that still counts as a dev dep and should not pull it in for a build).

**Comment by andylokandy** [comment] 2020-10-28 03:13
@koushiro Is that pr sufficient to close the issue?

**Comment by koushiro** [comment] 2020-10-28 04:14
@andylokandy  I'm waiting for #8817 to be merged, in which I removed all the dependencies associated with rand 0.6.

**Comment by LykxSassinator** [comment] 2024-12-18 11:02
Since https://github.com/tikv/tikv/pull/8817 was already merged, this issue can be closed safely.

**Closed by LykxSassinator** 2024-12-18 11:02 UTC
Labels: help wanted, component/build, difficulty/easy, component/build-time
