### ISSUE TITLE
RaftStore panicked with out of bounds access error

### ISSUE THREAD

**Issue by zyguan** [tikv/tikv#12046] opened 2022-02-28 08:59 UTC
### What version of TiKV are you using?

master @ cbcaab6ce56cdc0a503a5f9171470bff3c0b53da

### What operating system and CPU are you using?

kubernetes

### Steps to reproduce

Run jepsen monotonic test.

### What did you expect?

No unexpected panic of tikv during test.

### What did happened?

RaftStore panicked as the following log shown
```
[2022/02/27 10:11:04.211 +00:00] [FATAL] [lib.rs:466] ["Out of bounds access"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:465:18\n   1: std::panicking::rust_panic_with_hook\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:702:17\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:588:13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:138:18\n   4: rust_begin_unwind\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:584:5\n   5: core::panicking::panic_fmt\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:143:14\n   6: core::panicking::panic_display\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:73:5\n   7: core::panicking::panic_str\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:56:5\n   8: core::option::expect_failed\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/option.rs:1852:5\n   9: core::option::Option<T>::expect\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/option.rs:715:21\n      <alloc::collections::vec_deque::VecDeque<T,A> as core::ops::index::Index<usize>>::index\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/collections/vec_deque/mod.rs:2853:9\n      raftstore::store::read_queue::ReadIndexQueue<S>::advance_leader_reads\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/read_queue.rs:238:30\n      raftstore::store::peer::Peer<EK,ER>::apply_reads\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/peer.rs:2694:13\n      raftstore::store::peer::Peer<EK,ER>::handle_raft_ready_append\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/peer.rs:2092:9\n  10: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::collect_ready\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:1307:19\n      <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_normal\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:791:13\n  11: batch_system::batch::Poller<N,C,Handler>::poll\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:446:27\n  12: raftstore::store::worker::refresh_config::PoolController<N,C,H>::increase_by::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/worker/refresh_config.rs:71:21\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:122:18\n  13: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/thread/mod.rs:498:17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panic/unwind_safe.rs:271:9\n      std::panicking::try::do_call\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:492:40\n      std::panicking::try\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:456:19\n      std::panic::catch_unwind\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panic.rs:137:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/thread/mod.rs:497:30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/ops/function.rs:227:5\n  14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/boxed.rs:1854:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/boxed.rs:1854:9\n      std::sys::unix::thread::Thread::new::thread_start\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys/unix/thread.rs:108:17\n  15: start_thread\n  16: clone\n"] [location=/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/read_queue.rs:238] [thread_name=raftstore-7-0]
   0: tikv_util::set_panic_hook::{{closure}}
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:465:18
   1: std::panicking::rust_panic_with_hook
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:588:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:143:14
   6: core::panicking::panic_display
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:73:5
   7: core::panicking::panic_str
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:56:5
   8: core::option::expect_failed
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/option.rs:1852:5
   9: core::option::Option<T>::expect
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/option.rs:715:21
      <alloc::collections::vec_deque::VecDeque<T,A> as core::ops::index::Index<usize>>::index
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/collections/vec_deque/mod.rs:2853:9
      raftstore::store::read_queue::ReadIndexQueue<S>::advance_leader_reads
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/read_queue.rs:238:30
      raftstore::store::peer::Peer<EK,ER>::apply_reads
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/peer.rs:2694:13
      raftstore::store::peer::Peer<EK,ER>::handle_raft_ready_append
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/peer.rs:2092:9
  10: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::collect_ready
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:1307:19
      <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_normal
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:791:13
  11: batch_system::batch::Poller<N,C,Handler>::poll
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:446:27
  12: raftstore::store::worker::refresh_config::PoolController<N,C,H>::increase_by::{{closure}}
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/worker/refresh_config.rs:71:21
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:122:18
  13: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/thread/mod.rs:498:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panic.rs:137:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/thread/mod.rs:497:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/ops/function.rs:227:5
  14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/boxed.rs:1854:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/boxed.rs:1854:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys/unix/thread.rs:108:17
  15: start_thread
  16: clone
```
The full log can be accessed [here](http://minio.pingcap.net:9000/test-infra/2022-02-26/plan-exec-634870/plan-exec-634870-1335848004/archive.tgz).

**Comment by BusyJay** [comment] 2022-03-01 11:50
The only one way that can lead to the problem I can think of is https://github.com/tikv/tikv/pull/6348.

If a retry happens after all read states are committed inside the raft core, the raft can produce duplicated ready read states. What do you think? /cc @hicqu @5kbpers @NingLin-P

**Comment by you06** [comment] 2022-03-21 12:34
This issue blocks the release of 6.0 now, what's the progress of the investigation, is it still a blocking issue? @BusyJay

**Comment by BusyJay** [comment] 2022-03-21 12:48
Still no clue yet. Perhaps we should add more logs in case it's reproduced.

**Comment by tonyxuqqi** [comment] 2022-03-28 20:13
> The only one way that can lead to the problem I can think of is #6348.
> 
> If a retry happens after all read states are committed inside the raft core, the raft can produce duplicated ready read states. What do you think? /cc @hicqu @5kbpers @NingLin-P

#6348 retry_pending_reads() will skip on leader.  The callstack in this issue is in leader path. Could it be something else lead to this issue?

**Comment by BusyJay** [comment] 2022-03-29 08:22
My guess was wrong. I added more logs to check what happened. Luckily, it's not hard to reproduce.

**Comment by BusyJay** [comment] 2022-03-29 19:46
So the problem is packets travel too long in the network.

Supposing there are 3 peers a, b and c. If c is leader and inform both a and b. Then a and c are isolated from each other. If there is a replica read request to a, it will send a ReadIndexRequest to c and then buffer in the raft client. c then transfer leader to b, and then b transfer leader to a. At that time, the network is recovered. So the read index will be sent to c first, and then c will redirect to b, and then b redirect back to a. After handling the request, a consider the read states are part of the pending reads as the from field of the request is itself. However, the request is cleared back in the time when a just becomes leader. Hence lead to panic.

To fix the problem, we need to check if the read states can be found in contexts before panicking. Perhaps we should also filter all messages that from id is the peer itself. However, this can bring more side affects.

**Comment by tonyxuqqi** [comment] 2022-03-29 22:29
> So the problem is packets travel too long in the network.
> 
> Supposing there are 3 peers a, b and c. If c is leader and inform both a and b. Then a and c are isolated from each other. If there is a replica read request to a, it will send a ReadIndexRequest to c and then buffer in the raft client. c then transfer leader to b, and then b transfer leader to a. At that time, the network is recovered. So the read index will be sent to c first, and then c will redirect to b, and then b redirect back to a. After handling the request, a consider the read states are part of the pending reads as the from field of the request is itself. However, the request is cleared back in the time when a just becomes leader. Hence lead to panic.
> 
> To fix the problem, we need to check if the read states can be found in contexts before panicking. Perhaps we should also filter all messages that from id is the peer itself. However, this can bring more side affects.

will it be more safe to just filter ReadIndexRequest instead of all messages that from id is the peer itself.

**Comment by BusyJay** [comment] 2022-03-30 04:53
> will it be more safe to just filter ReadIndexRequest instead of all messages that from id is the peer itself.

Yes, that's exact how #12300 is implemented.

**Comment by NingLin-P** [comment] 2022-03-30 07:22
> To fix the problem, we need to check if the read states can be found in contexts before panicking. Perhaps we should also filter all messages that from id is the peer itself. However, this can bring more side affects.

How about instead changing
https://github.com/tikv/raft-rs/blob/2357cb22760719bcd107a90d1e64ef505bdb1e15/src/raft.rs#L2832
```rust
if req.from == INVALID_ID || req.from == self.id {
        let rs = ReadState {...};
        self.read_states.push(rs);
        return None;
}
```
to ignore the `req.from == self.id` case, which implies that the message is redirected from other peer

Since `RawNode::read_index` is the only place that generates `MsgReadIndex` and for the leader's read request, these messages should always be local message (where `req.from == INVALID_ID`) because the `read_only` queue will clear when role changed in `reset`.

**Comment by BusyJay** [comment] 2022-03-30 07:44
The raft message can be constructed by application and step as they are not considered local messages. Ignoring it in raft library is a broken change. Though I agree it's better fix the problem inside raft if we can ensure only `read_index` API is accepted to create the request.

**Closed** 2022-03-30 09:52 UTC
Labels: type/bug, sig/raft, severity/minor, affects-5.0, affects-5.1, affects-5.2, affects-5.3, affects-5.4, affects-6.0
