### ISSUE TITLE
We have some bad encoded-keys like: aaaa FF bbbb FF cccc 06 dd00 FE

### ISSUE THREAD

**Issue by imfantuan** [tikv/tikv#15896] opened 2023-11-01 07:09 UTC
## Bug Report

We got some BadPadding error when txn.scan our keys.
And we found some bad encoded-keys.

z195C9BD2E32AFE6A`FF`BA5883313B1C40BC`FF`5FBB8C713232714D`06`3772536E2E747300FE
z077BBB09103E1FBF`FF`DE4280443C5BAF6A`FF`498D1C7272347442`06`3577776C2E747300FE
z188fe7ba4b2b9d54`ff`dda3441f37dccd90`ff`41b66ec468794341`ff`644f30502e747300`fe` `fffffffffffffff5`

### What version of TiKV are you using?
tikv: v6.5.0 (set keys & when scan error happend)
go sdk: 2.0.5 (set keys)

tikv: v7.4.0 (still now work)
go sdk: 2.0.7 (still now work)

### Steps to reproduce
We have no idea.
We use txn.Set to set keys and txn.Tier to scan keys.

### What did you expect?
06 should be FF
fffffffffffffff5 should not exist

### What did happened?
hard to say.

pls help @pingyu

**Comment by pingyu** [comment] 2023-11-01 08:23
How you can these keys ?

The last key `z188fe7ba4b2b9d54ffdda3441f37dccd90ff41b66ec468794341ff644f30502e747300fefffffffffffffff5` may be correct. The `fffffffffffffff5` would be the timestamp.

**Comment by pingyu** [comment] 2023-11-01 09:33
It seems to be data corruption.

How many replicas do your cluster have, and whether other replica has the same wrong keys ? Please also check the health of disks.

If the issue is not relevant with hardware, the informations provided currently are not enough to address the issue. Please help to reproduce the problem.

**Comment by pingyu** [comment] 2023-11-01 15:07
Please provide the complete command & result of `tiup ctl tikv scan` of these 3 keys on all replicas if the key is on it.

Besides, is there RawKV workload on the cluster ?

**Comment by pingyu** [comment] 2023-11-03 01:33
> ## 3 error key (in region: 10768)
> We could not find it by using `tiup ctl:v7.4.0 tikv`,
> 
> however, we always get this error when scan by using txn.Iter(start, nil) with client-go, it shows the key name directly, so we no need to find it by using tikv ctl:
> 
> ```
> [WARN] [error.go:302] ["2PC failed"] [error="tikv aborts txn: Error(Txn(Error(Mvcc(Error(DefaultNotFound { key: [24, 143, 231, 186, 75, 43, 157, 84, 255, 221, 163, 68, 31, 55, 220, 205, 144, 255, 65, 182, 110, 196, 104, 121, 67, 65, 255, 100, 79, 48, 80, 46, 116, 115, 0, 254, 255, 255, 255, 255, 255, 255, 255, 245] })))))"] [errorVerbose="tikv aborts txn: Error(Txn(Error(Mvcc(Error(DefaultNotFound { key: [24, 143, 231, 186, 75, 43, 157, 84, 255, 221, 163, 68, 31, 55, 220, 205, 144, 255, 65, 182, 110, 196, 104, 121, 67, 65, 255, 100, 79, 48, 80, 46, 116, 115, 0, 254, 255, 255, 255, 255, 255, 255, 255, 245] })))))
> github.com/tikv/client-go/v2/error.ExtractKeyErr
> 	/Users/ethan/Desktop/go-server/vendor/github.com/tikv/client-go/v2/error/error.go:301
> github.com/tikv/client-go/v2/txnkv/txnlock.ExtractLockFromKeyErr
> 	/Users/ethan/Desktop/go-server/vendor/github.com/tikv/client-go/v2/txnkv/txnlock/lock.go:27
> github.com/tikv/client-go/v2/txnkv/txnsnapshot.(*Scanner).getData
> 	/Users/ethan/Desktop/go-server/vendor/github.com/tikv/client-go/v2/txnkv/txnsnapshot/scan.go:291
> github.com/tikv/client-go/v2/txnkv/txnsnapshot.(*Scanner).Next
> 	/Users/ethan/Desktop/go-server/vendor/github.com/tikv/client-go/v2/txnkv/txnsnapshot/scan.go:138
> github.com/tikv/client-go/v2/internal/unionstore.(*UnionIter).snapshotNext
> 	/Users/ethan/Desktop/go-server/vendor/github.com/tikv/client-go/v2/internal/unionstore/union_iter.go:81
> github.com/tikv/client-go/v2/internal/unionstore.(*UnionIter).Next
> 	/Users/ethan/Desktop/go-server/vendor/github.com/tikv/client-go/v2/internal/unionstore/union_iter.go:165
> go-server/scan.StartScan
> 	/Users/ethan/Desktop/go-server/scan/scan.go:73
> main.main
> 	/Users/ethan/Desktop/go-server/main.go:33
> runtime.main
> 	/usr/local/go/src/runtime/proc.go:250
> runtime.goexit
> 	/usr/local/go/src/runtime/asm_amd64.s:1598"]
> ```

`DefaultNotFound` means that the the committed entry existed in "write cf" not related value is not found in "default cf". Try `tiup ctl:v7.4.0 tiup scan` again with argument `--show-cf lock,default,write`.

**Comment by pingyu** [comment] 2023-11-03 05:33
The `start_ts: 10` should not be correct.

How you use `client-go` to perform business ? Can you show some codes of application closely related to`client-go`. Or just provide the address of repo if it's open source.

**Comment by pingyu** [comment] 2023-11-03 05:43
Please check whether there are some data file damaged. Refer to https://docs.pingcap.com/tidb/stable/tikv-control#print-information-related-to-damaged-sst-files.

**Comment by pingyu** [comment] 2023-11-03 07:44
> 1. We import these (group A) data on Mar.07;

How did you import data ?

> 4. 1/3 tikv server shuted down, can not restart;

Why can not restart ? Please provide error logs if there is any.

**Comment by pingyu** [comment] 2023-11-03 08:39
> > > 1. We import these (group A) data on Mar.07;
> > 
> > 
> > How did you import data ?
> 
> By using this: https://github.com/seaweedfs/seaweedfs/tree/master/weed/filer/tikv
> 

So it's `KvPut` underlying ?

**Comment by pingyu** [comment] 2023-11-05 06:59
> By the way... how could we just delete them?

You can use RawKV API to delete the wrong keys. Use with caption.

Refer to https://github.com/tikv/client-go/wiki/RawKV-Basic#single-key-readwrite.

**Comment by pingyu** [comment] 2023-11-05 07:26
> Here are some infomations:
> 
> 1. We import these (group A) data on Mar.07;
> 2. We scan all data after import found 66,968,762 keys (no BadPadding or DefaultNotFound errors);
> 3. Import many other (group B) data ( ≈ 20000000+ );
> 4. 1/3 tikv server shuted down, can not restart;
> 5. We scale-in that by using --force on tiup server (and scale-out to another server);
> 6. Got BadPadding and DefaultNotFound errors when we scan all data (all 3 incorrect keys are belongs to group A data).

When 1/3 TiKV servers shut down, it's very likely that some regions lost majority. Have you ever perform any unsafe recover ?

Please collect and upload diagnostic data, including metrics and logs, of the whole day(s) when TiKV servers shutting down and scaling in/out happened. Refer to https://docs.pingcap.com/tidb/stable/quick-start-with-clinic.

**Comment by tonyxuqqi** [comment] 2024-01-29 18:40
@imfantuan Since we don't have enough information, we will close this issue for now. Please reopen if you have full diagnostics information.

**Closed by tonyxuqqi** 2024-01-29 18:40 UTC
Labels: type/bug
