### ISSUE TITLE
build tikv failed

### ISSUE THREAD

**Issue by newHE3DBer** [tikv/tikv#10106] opened 2021-04-30 01:04 UTC
## Question
build tikv release4.0 failed

**Comment by newHE3DBer** [comment] 2021-04-30 01:05
![Uploading image.png…]()

**Comment by newHE3DBer** [comment] 2021-04-30 01:12
Compiling yatp v0.0.1 (https://github.com/tikv/yatp.git?branch=tikv-4.0#8d739275)
error[E0599]: no method named `as_raw` found for struct `std::sync::Weak<QueueCore<T>>` in the current scope
   --> /root/.cargo/git/checkouts/yatp-e704b73c3ee279b6/8d73927/src/pool/spawn.rs:192:19
    |
192 |         self.core.as_raw()
    |                   ^^^^^^ method not found in `std::sync::Weak<QueueCore<T>>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `yatp`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [release] 错误 101

**Comment by hi-rustin** [comment] 2021-05-06 12:36
Can you provide more information please? For example, the environment, the rustc version, and the compilation steps.

**Comment by newHE3DBer** [comment] 2021-05-07 12:53
rustc 1.51.0-nightly (1d0d76f8d 2021-01-24)
![image](https://user-images.githubusercontent.com/71053140/117452316-311e4080-af76-11eb-9c50-36d5e612ef93.png)

![image](https://user-images.githubusercontent.com/71053140/117452398-4bf0b500-af76-11eb-9581-e03a30f8ffd3.png)

**Comment by hi-rustin** [comment] 2021-05-08 02:19
**I can't reproduce this.** Finished release [optimized] target(s) in 21m 03s.

The env: macOS Catalina 10.15.7 19H2 x86_64
The rustc: rustc 1.42.0-nightly (0de96d37f 2019-12-19)

You need to use the corresponding rust-toolchain instead of using the latest version.

**Comment by hi-rustin** [comment] 2021-05-16 13:44
I will close this issue, but if you have any other questions you can comment afterwards.

/close

**Closed by hi-rustin** 2021-05-16 13:44 UTC
