### ISSUE TITLE
resolved ts stuck for 10m when TiKV failure restored. 

### ISSUE THREAD

**Issue by fubinzh** [tikv/tikv#16741] opened 2024-04-02 09:02 UTC
### What version of TiKV are you using?
v8.0
git_hash: 9f51dfed1f04224a746facfbd919ae8ebec639eb

### What operating system and CPU are you using?
X86, K8S

### Steps to reproduce
1. TiDB cluster with titan on, cluster with 30 TiKV nodes, cluster size: 70TB, througtput ~40MB/s
2.  CDC changefeed running to sync 4000 tables.
3.  Inject one TiKV failure for 50m
4. Check cdc lag after TiKV failure restored

### What did you expect?
CDC lag should not be >10s

### What did happened?
CDC lag is OK during chaos injection (3/29 22:01 - 22:51), however resolved ts stuck for 10m when TiKV failure restored.

![img_v3_029h_580a9453-2800-4ccc-aa40-ef08e4b63c6g](https://github.com/tikv/tikv/assets/7403864/efe68925-3c38-4263-897b-4815c080f0a4)
![img_v3_029h_8b25ffbd-86a5-4e5f-84a5-3ee7ef1d8a9g](https://github.com/tikv/tikv/assets/7403864/8c61546b-90c7-45d3-baff-fc04338c19a7)

**Comment by LykxSassinator** [comment] 2024-04-02 09:11
Dup with https://github.com/tikv/tikv/issues/12259

**Comment by fubinzh** [comment] 2024-05-09 09:13
Retested this scenario with https://github.com/tikv/tikv/pull/16738, this PR worked as expected for mitigating the jitters of QPS when restarting TiKV nodes.
But CDC lag still up to 5min as too many memory consumption during redo apply, which triggers log replication rejection. This need further optimization per https://github.com/tikv/tikv/issues/12259#issuecomment-2100194769

Steps:
1. TiKV hash before chaos inject: 56613f7c3e28c02853cc51d15bc1b77f68b58be8
2. 14:44 - 15:34 Inject TiKV random node failure.
3. TiKV restarted after chaos injection recovered, TiKV hash: befa08ef6af45ff39762f39bb59421b8750f11c4
4. CDC lag up to 5min after chaos restored
![img_v3_02an_5f4d9f3d-72ae-4301-a760-3b2e0640fdbg](https://github.com/tikv/tikv/assets/7403864/4befaad8-2562-4203-b9be-37f78ee12413)
![img_v3_02an_58109672-d753-4a43-9414-0c64928b12cg](https://github.com/tikv/tikv/assets/7403864/0039cd22-e2e4-4153-b35e-f585be1e0297)
![img_v3_02an_ef1775d0-aed4-46e2-97dc-ca2be5c49dag](https://github.com/tikv/tikv/assets/7403864/24d1568b-b529-4083-9107-f67c7389a29f)
![img_v3_02an_f1b7eda2-dbf8-4912-9f38-d9cb375a091g](https://github.com/tikv/tikv/assets/7403864/acdfb7eb-a454-4c9c-9aa8-b128e8308207)
![img_v3_02an_05176f30-cf8a-4861-838a-815d5cfee28g](https://github.com/tikv/tikv/assets/7403864/86beba22-c07f-47ba-8dc5-22c88edee11d)

**Comment by fubinzh** [comment] 2024-08-06 06:50
Retested this scenario 4 times with v8.2.0 clustser, CDC lag is below 10s during chaos injection in general with very few spikes of ~30s.

4 TiKV random failures injection details as below:
1. 8/1 11：17 - 12：07 TiKV random failure injection for 50m
2. 8/1  12：55 - 13：45 TiKV random failure injection for 50m
3. 8/1  15：16 - 16：06 TiKV random failure injection for 50m
4. 8/1 17:06 - 17:56 TiKV random failure injection for 50m

![image](https://github.com/user-attachments/assets/d840513f-b40d-42ec-89f1-a7fc2848f958)
![image](https://github.com/user-attachments/assets/245f8599-3967-47ae-9c13-9b413b8d717d)


Cluster Details:
- Cluster size: 22TB
- TiKV 16c64g * 9, total regions: 83k
![image](https://github.com/user-attachments/assets/981e2c60-fdd1-416c-8846-7d0d0e64c158)

- Cluster with 5 schemas and 5.2K+ tables, table details as below.
![image](https://github.com/user-attachments/assets/286f52db-e8b1-427d-ba82-b0928e958163)
- There are 14 changfeeds (kafka simple protocol) created for the 5.2k tables.
    - for the 5k, 100k, 500k, 2m schemas, each schema is synced by one changefeed. i.e. 4 changefeed in total, each replicating 1000, 250, 10 2 tables respectively.
    - for  the 1k schemas ( 4000 tables), 10 changefeed created, and each changefeed replicating 400 tables.
- Workload: throughtput ranges from ~20MB/s to ~80MB/s for different testings.
![image](https://github.com/user-attachments/assets/8e024a67-7f25-4748-92a5-81f9aef18f90)

```
[root@upstream-ticdc-0 /]# /cdc version
Release Version: v8.2.0
Git Commit Hash: 498e3d3fd1cda4817e70ea50d27dcb157956349d
Git Branch: HEAD
UTC Build Time: 2024-07-03 02:52:36
Go Version: go version go1.21.10 linux/amd64
Failpoint Build: false

[root@upstream-tikv-0 /]# /tikv-server -V
TiKV 
Release Version:   8.2.0
Edition:           Community
Git Commit Hash:   6e50b27980d7d2795c2d662c7a11d03d81d4b64d
Git Commit Branch: HEAD
UTC Build Time:    2024-07-09 08:09:03
Rust Version:      rustc 1.77.0-nightly (89e2160c4 2023-12-27)
Enable Features:   memory-engine pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine trace-async-tasks openssl-vendored
Profile:           dist_release
```

**Comment by LykxSassinator** [comment] 2024-08-06 07:04
Thx. 

It's expected while the jitters of the lag is caused by the leader transferring and it should update the leader info by triggering new `CheckLeader` RPCs.

**Closed** 2024-08-06 09:27 UTC
Labels: type/bug
