### ISSUE TITLE
coprocessor: parsing error is never returned

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#4293] opened 2019-02-27 15:57 UTC
When it fails to parse a request, the error is wrapped in an dummy handler which is returned from the function with a fake context and supposed to be executed inside read pool.

https://github.com/tikv/tikv/blob/e53a8c21d77d8ce0e06b855fbe31ee9f8cd525a2/src/coprocessor/endpoint.rs#L196-L211

However endpoint will continue to get a snapshot first using the fake context, which will always fail as it's an invalid context.

https://github.com/tikv/tikv/blob/e53a8c21d77d8ce0e06b855fbe31ee9f8cd525a2/src/coprocessor/endpoint.rs#L344-L357

So a strange error from raftstore is returned instead of the actual error which is the parsing error in the first place.

The bug is introduced in #3515, and affects v2.1.x and v3.0.x, needs to be fixed soon.

@disksing @breeswish PTAL

**Comment by siddontang** [comment] 2019-02-27 16:01
Finally, we find this problem 😭 

Btw, why parsing failed? the request is too big? @BusyJay

**Comment by disksing** [comment] 2019-02-27 16:07
The request can be unmarshalled in Go. I guess the problem is the  DAG request recurses too deep.

**Comment by breeswish** [comment] 2019-02-27 16:50
Interesting finding. Looks like we must find a way that parsing failed errors are returned immediately instead of partially finished the pipe line.

**Comment by breeswish** [comment] 2019-03-18 06:57
Fixed in #4303

**Closed by breeswish** 2019-03-18 06:57 UTC
Labels: C: Copr, T: Bug
