### ISSUE TITLE
raftstore v2: A region's peer may be stolen by another region and cause destruction of its Leader peer

### ISSUE THREAD

**Issue by CalvinNeo** [tikv/tikv#15439] opened 2023-08-25 03:34 UTC
## Bug Report

This seems to happen in a merging situation where region 14277 want to be merged into 12462.

Check the following log, the peer 14280 is of region 14277. However, it suddenly becomes to a peer with larger ID of region 12462. This will destroy the region 12462's original peer 12465, which is actually a leader.
```
// At this timepoint, peer became Leader of region 12462
[2023/08/22 09:41:46.609 +08:00] [INFO] [raft.rs:1306] ["broadcasting vote request"] [to="[12464, 12463]"] [log_index=11325] [log_term=8] [term=8] [type=MsgRequestPreVote] [raft_id=12465] [peer_id=12465] [region_id=12462]
[2023/08/22 09:41:46.610 +08:00] [INFO] [raft.rs:2219] ["received votes response"] [term=8] [type=MsgRequestPreVoteResponse] [approvals=2] [rejections=0] [from=12464] [vote=true] [raft_id=12465] [peer_id=12465] [region_id=12462]
[2023/08/22 09:41:46.610 +08:00] [INFO] [raft.rs:1151] ["became candidate at term 9"] [term=9] [raft_id=12465] [peer_id=12465] [region_id=12462]
[2023/08/22 09:41:46.610 +08:00] [INFO] [raft.rs:1306] ["broadcasting vote request"] [to="[12464, 12463]"] [log_index=11325] [log_term=8] [term=9] [type=MsgRequestVote] [raft_id=12465] [peer_id=12465] [region_id=12462]
[2023/08/22 09:41:46.610 +08:00] [INFO] [raft.rs:2219] ["received votes response"] [term=9] [type=MsgRequestVoteResponse] [approvals=2] [rejections=0] [from=12464] [vote=true] [raft_id=12465] [peer_id=12465] [region_id=12462]
[2023/08/22 09:41:46.610 +08:00] [INFO] [raft.rs:1235] ["became leader at term 9"] [term=9] [raft_id=12465] [peer_id=12465] [region_id=12462]
[2023/08/22 09:41:46.610 +08:00] [INFO] [txn_ext.rs:122] ["require updating max ts"] [initial_status=38654706024] [peer_id=12465] [region_id=12462]
[2023/08/22 09:41:46.611 +08:00] [INFO] [misc.rs:92] ["succeed to update max timestamp"] [region_id=12462]

// However, it is then destroyed for some strange reason
[2023/08/22 09:41:52.605 +08:00] [INFO] [raft.rs:1557] ["starting a new election"] [term=8] [raft_id=14280] [peer_id=14280] [region_id=14277]
[2023/08/22 09:41:52.684 +08:00] [INFO] [mod.rs:366] ["mark for destroy for larger ID"] [larger_id=14280] [peer_id=12465] [region_id=12462]
```
After the destroy happens, the region 12462 will bootstrap a new peer with id=14280. The following log is from TiKV1, which is region leader previously.
```
[2023/08/22 09:41:52.685 +08:00] [INFO] [life.rs:846] ["peer destroyed"] [peer_id=12465] [region_id=12462]
[2023/08/22 09:41:52.685 +08:00] [INFO] [router.rs:348] ["shutdown mailbox"] [region_id=12462]
[2023/08/22 09:41:52.685 +08:00] [INFO] [raft.rs:2663] ["switched to configuration"] [config="Configuration { voters: Configuration { incoming: Configuration { voters: {} }, outgoing: Configuration { voters: {} } }, learners: {}, learners_next: {}, auto_leave: false }"] [raft_id=14280] [peer_id=14280] [region_id=12462]
[2023/08/22 09:41:52.685 +08:00] [INFO] [raft.rs:1127] ["became follower at term 0"] [term=0] [raft_id=14280] [peer_id=14280] [region_id=12462]
[2023/08/22 09:41:52.685 +08:00] [INFO] [raft.rs:388] [newRaft] [peers="Configuration { incoming: Configuration { voters: {} }, outgoing: Configuration { voters: {} } }"] ["last term"=0] ["last index"=0] [applied=0] [commit=0] [term=0] [raft_id=14280] [peer_id=14280] [region_id=12462]
[2023/08/22 09:41:52.685 +08:00] [INFO] [raw_node.rs:315] ["RawNode created with id 14280."] [id=14280] [raft_id=14280] [peer_id=14280] [region_id=12462]
[2023/08/22 09:41:52.685 +08:00] [INFO] [peer.rs:50] ["create peer"] [region_state="region { id: 12462 region_epoch { conf_ver: 37 version: 180 } peers { id: 12467 store_id: 27 role: Learner } peers { id: 14280 store_id: 4 } }"] [apply_state=] [raft_state="hard_state {}"] [peer_id=14280] [region_id=12462]
[2023/08/22 09:41:52.690 +08:00] [INFO] [endpoint.rs:342] ["register observe region"] [region="id: 14277 start_key: 7480000000000001FF5B5F728000000000FF7856640000000000FA end_key: 7480000000000001FF5B5F728000000000FF7856650000000000FA region_epoch { conf_ver: 49 version: 181 } peers { id: 14278 store_id: 1 } peers { id: 14280 store_id: 4 } peers { id: 14281 store_id: 19 role: Learner } peers { id: 14282 store_id: 27 role: Learner } peers { id: 16796 store_id: 26 }"]
```
After then the new peer 14280 established, without any information about the region 12462. Since it has no information about its peers, it can't elect.
```
[2023/08/22 09:43:25.095 +08:00] [INFO] [mod.rs:250] ["failed to propose admin command"] [error="Other(\"[components/raftstore-v2/src/operation/command/admin/merge/prepare.rs:266]: target region not matched, skip proposing: id: 12462 region_epoch { conf_ver: 37 version: 180 } peers { id: 12467 store_id: 27 role: Learner } peers { id: 14280 store_id: 4 } != id: 12462 start_key: 7480000000000001FF5B5F728000000000FF7856650000000000FA end_key: 7480000000000001FF5B5F728000000000FF87BD360000000000FA region_epoch { conf_ver: 37 version: 180 } peers { id: 12463 store_id: 1 } peers { id: 12464 store_id: 26 } peers { id: 12465 store_id: 4 } peers { id: 12466 store_id: 19 role: Learner } peers { id: 12467 store_id: 27 role: Learner }\")"] [cmd_type=PrepareMerge] [peer_id=14280] [region_id=14277]
```

### What version of TiKV are you using?

nightly

### What operating system and CPU are you using?

na

### What did you expect?
Leader can be elected

### What did happened?
Leader can not be elected

**Comment by CalvinNeo** [comment] 2023-08-25 06:26
In another tikv instance(tikv3), we noticed the similar logs
```
[2023/08/22 07:45:03.816 +08:00] [INFO] [compact_log.rs:588] ["compact log"] [truncated="applied_index: 8515 truncated_state { index: 8514 term: 7 }"] [apply_trace="ApplyTrace { data_cfs: [Progress { flushed: 5, last_modified: 5 }, Progress { flushed: 8514, last_modified: 8514 }, Progress { flushed: 8514, last_modified: 8514 }], admin: Progress { flushed: 8515, last_modified: 8515 }, persisted_applied: 8515, last_flush_trigger: 0, try_persist: false }"] [index=8515] [peer_id=14278] [region_id=14277]

[2023/08/22 09:15:34.124 +08:00] [INFO] [mod.rs:366] ["mark for destroy for larger ID"] [larger_id=14278] [peer_id=12463] [region_id=12462]
[2023/08/22 09:15:34.124 +08:00] [INFO] [life.rs:846] ["peer destroyed"] [peer_id=12463] [region_id=12462]
[2023/08/22 09:15:34.124 +08:00] [INFO] [router.rs:348] ["shutdown mailbox"] [region_id=12462]
[2023/08/22 09:15:34.124 +08:00] [INFO] [raft.rs:2663] ["switched to configuration"] [config="Configuration { voters: Configuration { incoming: Configuration { voters: {} }, outgoing: Configuration { voters: {} } }, learners: {}, learners_next: {}, auto_leave: false }"] [raft_id=14278] [peer_id=14278] [region_id=12462]
[2023/08/22 09:15:34.124 +08:00] [INFO] [raft.rs:1127] ["became follower at term 0"] [term=0] [raft_id=14278] [peer_id=14278] [region_id=12462]
[2023/08/22 09:15:34.124 +08:00] [INFO] [raft.rs:388] [newRaft] [peers="Configuration { incoming: Configuration { voters: {} }, outgoing: Configuration { voters: {} } }"] ["last term"=0] ["last index"=0] [applied=0] [commit=0] [term=0] [raft_id=14278] [peer_id=14278] [region_id=12462]

[2023/08/22 09:41:34.100 +08:00] [INFO] [mod.rs:250] ["failed to propose admin command"] [error="Other(\"[components/raftstore-v2/src/operation/command/admin/merge/prepare.rs:266]: target region not matched, skip proposing: id: 12462 region_epoch { conf_ver: 37 version: 180 } peers { id: 12466 store_id: 19 role: Learner } peers { id: 14278 store_id: 1 } != id: 12462 start_key: 7480000000000001FF5B5F728000000000FF7856650000000000FA end_key: 7480000000000001FF5B5F728000000000FF87BD360000000000FA region_epoch { conf_ver: 37 version: 180 } peers { id: 12463 store_id: 1 } peers { id: 12464 store_id: 26 } peers { id: 12465 store_id: 4 } peers { id: 12466 store_id: 19 role: Learner } peers { id: 12467 store_id: 27 role: Learner }\")"] [cmd_type=PrepareMerge] [peer_id=14278] [region_id=14277]
[2023/08/22 09:41:39.100 +08:00] [INFO] [region.rs:317] ["try to merge"] [merge="target { id: 12462 start_key: 7480000000000001FF5B5F728000000000FF7856650000000000FA end_key: 7480000000000001FF5B5F728000000000FF87BD360000000000FA region_epoch { conf_ver: 37 version: 180 } peers { id: 12463 store_id: 1 } peers { id: 12464 store_id: 26 } peers { id: 12465 store_id: 4 } peers { id: 12466 store_id: 19 role: Learner } peers { id: 12467 store_id: 27 role: Learner } }"] [region_id=14277]
```

**Comment by CalvinNeo** [comment] 2023-08-25 07:59
In TiFlash2's log
```
[2023/08/22 07:42:21.229 +08:00] [INFO] [apply.rs:1690] ["execute admin command"] [command="cmd_type: BatchSplit splits { requests { split_key: 7480000000000001FF5B5F728000000000FF422BB60000000000FA new_region_id: 14265 new_peer_ids: 14266 new_peer_ids: 14267 new_peer_ids: 14268 new_peer_ids: 14269 new_peer_ids: 14270 } requests { split_key: 7480000000000001FF5B5F728000000000FF5D43010000000000FA new_region_id: 14271 new_peer_ids: 14272 new_peer_ids: 14273 new_peer_ids: 14274 new_peer_ids: 14275 new_peer_ids: 14276 } requests { split_key: 7480000000000001FF5B5F728000000000FF7856650000000000FA new_region_id: 14277 new_peer_ids: 14278 new_peer_ids: 14279 new_peer_ids: 14280 new_peer_ids: 14281 new_peer_ids: 14282 } right_derive: true }"] [index=9] [term=8] [peer_id=12467] [region_id=12462]
[2023/08/22 07:42:21.229 +08:00] [INFO] [command.rs:236] ["observe admin command"] [region_epoch="conf_ver: 37 version: 177"] [command="cmd_type: BatchSplit splits { requests { split_key: 7480000000000001FF5B5F728000000000FF422BB60000000000FA new_region_id: 14265 new_peer_ids: 14266 new_peer_ids: 14267 new_peer_ids: 14268 new_peer_ids: 14269 new_peer_ids: 14270 } requests { split_key: 7480000000000001FF5B5F728000000000FF5D43010000000000FA new_region_id: 14271 new_peer_ids: 14272 new_peer_ids: 14273 new_peer_ids: 14274 new_peer_ids: 14275 new_peer_ids: 14276 } requests { split_key: 7480000000000001FF5B5F728000000000FF7856650000000000FA new_region_id: 14277 new_peer_ids: 14278 new_peer_ids: 14279 new_peer_ids: 14280 new_peer_ids: 14281 new_peer_ids: 14282 } right_derive: true }"] [index=9] [term=8] [peer_id=12467] [region_id=12462]
[2023/08/22 07:42:21.231 +08:00] [INFO] [peer.rs:4113] ["insert new region"] [region="id: 14277 start_key: 7480000000000001FF5B5F728000000000FF5D43010000000000FA end_key: 7480000000000001FF5B5F728000000000FF7856650000000000FA region_epoch { conf_ver: 37 version: 180 } peers { id: 14278 store_id: 1 } peers { id: 14279 store_id: 26 } peers { id: 14280 store_id: 4 } peers { id: 14281 store_id: 19 role: Learner } peers { id: 14282 store_id: 27 role: Learner }"] [region_id=14277]
```

**Comment by tonyxuqqi** [comment] 2023-09-25 23:19
Is it reproed without TiFlash? @CalvinNeo

**Comment by overvenus** [comment] 2023-09-27 07:53
It might be caused by https://github.com/tikv/tikv/issues/15623#issuecomment-1723172816, which is fixed by https://github.com/tikv/tikv/pull/15643.

Please open if it happens again.

**Closed by overvenus** 2023-09-27 07:53 UTC
Labels: type/bug, severity/critical, feature/developing, may-affects-5.3, may-affects-5.4, may-affects-6.1, may-affects-6.5, may-affects-7.1, affects-7.4
