### ISSUE TITLE
Cargo Run workflow no longer usable

### ISSUE THREAD

**Issue by Hoverbear** [tikv/tikv#5289] opened 2019-08-15 19:47 UTC
## Bug Report

**What version of TiKV are you using?**
master

**What operating system and CPU are you using?**
Any

**What did you do?**

As is convention in the Rust ecosystem, as I have for the last year and a half, I ran `cargo run --bin tikv-server` to start a TiKV development build of the server.

The command reported:

```
error: no bin target named `tikv-server`
```

The README.md does not describe how to workaround this problem.

The target machine does not have access to a copy of `make` that can support the complex Makefile.

**What did you expect to see?**

TiKV, as a rust project, to build and operate like a Rust project.

TiKV, as a repository of tikv project, should follow the conventions of our other rust projects and support a clean `cargo run` behavior.

**What did you see instead?**

```
error: no bin target named `tikv-server`
```

## What action should be taken?

I suggest reverting https://github.com/tikv/tikv/pull/5242 or adding documentation to all of our README files, as well as our `/Cargo.toml` documenting this.

I would prefer reverting https://github.com/tikv/tikv/pull/5242. I think this has very poor usability for folks trying out contributing or developing TiKV for their first time.

**Comment by Hoverbear** [comment] 2019-08-15 19:47
What do you think, @overvenus ?

**Comment by Hoverbear** [comment] 2019-08-15 20:39
@nrc suggested:

> we might be able to use default-bin to make just cargo run work

**Comment by overvenus** [comment] 2019-08-16 10:48
I prefer adding documentation.

The actual workflow of TiKV is based on Makefile. Eg. cargo test does not test crates under components. So we should use `make run` instead of `cargo run`.

The point of #5242 is to prevent cyclin-dependent when we add a new crate (depends on the tikv) into tikv-server.

**Comment by Hoverbear** [comment] 2019-08-16 18:39
@overvenus I'm not sure breaking this workflow is worth it. :(

**Comment by nrc** [comment] 2019-08-18 20:57
I hope we can get the benefits of both sides - it is nice to move out the cmd crate because the dependencies in the TiKV workspace are a bit of a nightmare (for the Prost work I must move out the tests into their own crate too). OTOH, it is *really good* for new contributors if the Cargo workflows work (even if they are not doing the optimal things). Using Cargo is very standard in the Rust community.

**Comment by Hoverbear** [comment] 2019-08-19 19:26
This also impacts cargo tooling like `cargo metadata`, `cargo tree`, ...

**Comment by Hoverbear** [comment] 2019-08-19 19:26
@overvenus Can I propose I write a new checker for you some other way and we include it as a make task?

**Comment by Hoverbear** [comment] 2019-08-19 22:37
This may also impact our `Dockerfiles` https://github.com/tikv/tikv/blob/6a516eea06906a96efd0223245ac90531faa4dec/scripts/gen-dockerfile.sh#L58

**Comment by overvenus** [comment] 2019-08-21 02:18
Sorry for breaking `gen-dockerfile.sh`, will be fixed today. 

I really need the `cmd` crate, because I will soon add new a component, which depends on `tikv`, into tikv-server.

**Comment by Hoverbear** [comment] 2019-08-21 16:59
@overvenus OK. Can we still support `cargo run --bin tikv-server` somehow.

Do you think we could add a proxy binary there that just invokes `cmd::tikv_server`? This might also make it possible to move `cmd` into the `components/` directory.

**Comment by overvenus** [comment] 2019-08-22 01:08
> Can we still support cargo run --bin tikv-server somehow?

I don't have a clear plan to support this, could you help me?

> This might also make it possible to move cmd into the components/ directory.

Putting `cmd` out of components is suggested by @siddontang https://github.com/tikv/tikv/pull/5242#issuecomment-519821991

**Comment by Hoverbear** [comment] 2019-08-22 01:39
Hm, I hear from @siddontang that `tikv-ctl` may merge with `tikv-server`...

Can you please explain to me exactly what is preventing us from having `/src/bin/tikv-server.rs` instead?

You say you're adding a new crate that depends on TIKV? Maybe we should be separating tikv-server into a separate project/repo?

**Comment by siddontang** [comment] 2019-08-22 01:54
> Hm, I hear from @siddontang that tikv-ctl may merge with tikv-server...

Not now, but in the near future @Hoverbear see #4908

**Comment by brson** [comment] 2019-09-05 21:34
I also agree that `cargo run` should just work.

If the problem is that tikv-server/ctl is going to depend on a library that itself depends on tikv, then we can make tikv another 'component' and make the top-level manifest just hold the bins.

**Comment by brson** [comment] 2019-09-05 21:42
Also we might use the new (?) [default-run](https://doc.rust-lang.org/cargo/reference/manifest.html#the-default-run-field) key to make tikv-server run without picking an explicit bin

**Comment by brson** [comment] 2019-09-05 21:44
Also the [default-members](https://doc.rust-lang.org/cargo/reference/manifest.html#package-selection) key might help us here. It specifies the "main" package".

Since tikv is so huge now it probably would make sense to turn the main manifest into a pure workspace, and put everything into a sub-component, then use default-members and maybe default-run.

**Comment by Hoverbear** [comment] 2019-09-09 01:43
Related to https://github.com/tikv/tikv/pull/5374

**Comment by aknuds1** [comment] 2019-09-09 05:18
@brson's suggestions sound sensible to me.

**Comment by Hoverbear** [comment] 2019-09-09 22:37
Let me have a try!

**Closed** 2019-09-10 02:59 UTC
Labels: T: Bug
