### ISSUE TITLE
GC is always triggered on idle cluster

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#6165] opened 2019-12-05 12:02 UTC
one TiKV with one TiDB
GC cause a lot of seek every 10 minutes, whereas no write in the time span.
<img width="916" alt="屏幕快照 2019-12-05 下午7 57 03" src="https://user-images.githubusercontent.com/13497871/70233593-df2e2580-1799-11ea-817b-16adc47f6af5.png">
<img width="917" alt="屏幕快照 2019-12-05 下午7 56 39" src="https://user-images.githubusercontent.com/13497871/70233594-df2e2580-1799-11ea-81ba-05194c3cc118.png">

**Comment by zhangjinpeng1987** [comment] 2020-11-05 06:58
It is caused by the property's deviation, if we want to prevent it we should consider adding some write flow statistics for each region. But after we import the compaction filter feature, this issue will not exist, so close it now.

**Closed by zhangjinpeng1987** 2020-11-05 06:58 UTC
Labels: priority/low, severity/Minor, sig/transaction, status/help-wanted, type/bug
