### ISSUE TITLE
TiKV panic because the buffer size in log_batch is more than 2G when append to RaftEngine.

### ISSUE THREAD

**Issue by joccau** [tikv/tikv#13848] opened 2022-11-27 08:13 UTC
### What version of TiKV are you using?
V6.4.0 
```
195295 [2022/11/25 17:57:34.327 +08:00] [FATAL] [lib.rs:495] ["called `Result::unwrap()` on an `Err` value: Other(\"[components/raft_log_engine/src/engine.rs:647]: Full\")"] [backtrace=" 0: tikv_util::set_panic_hook::{{closure}}
 at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:494:18
 1: std::panicking::rust_panic_with_hook
 at /rust/toolchains/nightly-2022-07-31-x86_64-unkn own-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:702:17
 2: std::panicking::begin_panic_handler::{{closure}}
 at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/libra ry/std/src/panicking.rs:588:13
 3: std::sys_common::backtrace::__rust_end_short_backtrace
 at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs :138:18
 4: rust_begin_unwind
 at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:584:5
 5: core::panicking::panic_fmt
 at /rust/toolcha ins/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:142:14
 6: core::result::unwrap_failed
 at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/ src/rust/library/core/src/result.rs:1814:5
 7: core::result::Result<T,E>::unwrap
 at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1107:23
 raftst ore::store::async_io::write::WriteTaskBatch<EK,ER>::add_write_task
 at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/async_io/write.rs:394:9
 raftstore:: store::async_io::write::Worker<EK,ER,N,T>::handle_write_task
 at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/async_io/write.rs:665:9
 8: raftstore::store: :async_io::write::Worker<EK,ER,N,T>::handle_msg
 at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/async_io/write.rs:652:17
 9: raftstore::store::async_io::w rite::Worker<EK,ER,N,T>::run
 at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/async_io/write.rs:595:32
 raftstore::store::async_io::write::StoreWriters< EK,ER>::spawn::{{closure}}
 at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/async_io/write.rs:906:21
 <std::thread::Builder as tikv_util::sys::thread::S tdThreadBuildWrapper>::spawn_wrapper::{{closure}}
 at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:415:23
 std::sys_common::backtrace::__rust_be gin_short_backtrace
 at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:122:18
 10: std::thread::Builder::spawn_unchecked_::{{closure}}::{{clo sure}}
 at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:505:17
 <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()> >::call_once
 at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:271:9
 std::panicking::try::do_call
 at /rust/toolchains/night ly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:492:40
 std::panicking::try
 at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/s td/src/panicking.rs:456:19
 std::panic::catch_unwind
 at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14
 std::thread::Builder::spawn_unchec ked_::{{closure}}
 at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:504:30
 core::ops::function::FnOnce::call_once{{vtable.shim}}
 at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:248:5
 11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
 at /rust/toolch ains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1935:9
 <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
 at /rust/toolchains/nightly-2022- 07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1935:9
 std::sys::unix::thread::Thread::new::thread_start
 at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustli b/src/rust/library/std/src/sys/unix/thread.rs:108:17
 12: start_thread
 13: clone
```

When the the buffer in log_batch is larger than 2G, it resturns Err(). 
https://github.com/tikv/raft-engine/blob/c01135d9ad9dd550b3aeda87963b3527f5b31fbb/src/log_batch.rs#L618

**Comment by 3pointer** [comment] 2023-03-03 12:05
reopen this issue since it reproduce on latest release-6.5 (112123e787665c557a50d12ade185380d1b6c882)

**Comment by tonyxuqqi** [comment] 2023-07-07 01:45
fixed by restore code

**Comment by YuJuncen** [comment] 2023-09-22 10:17
Reopen this since https://github.com/tikv/tikv/pull/14363 cannot be (at least trivially) cherry-picked to release-6.5.

**Comment by YuJuncen** [comment] 2023-09-22 10:29
Generally #13463 requires https://github.com/tikv/tikv/pull/14294 to implement, due to it relies on the TLS Engine. But for all release 6.5 versions, we didn't use Engine at all. Perhaps we need to rebuild a TLS RaftStoreRouter(TBH I would prefer just wrapping it with mutex...) or go back to the local executor. Each of which is painful.

(If I recall right, is there a patch that restricts the per-region concurrency?)

But anyway perhaps #13463 is needed for the performance of restoring, and the metrics will get inconsistent between v6.5.x and v7.1.x or higher.

**Comment by tonyxuqqi** [comment] 2023-10-23 23:35
It should be fixed by https://github.com/tikv/tikv/issues/15036 as well

**Closed** 2024-01-29 23:59 UTC
Labels: type/bug, severity/major, affects-6.5

**Comment by guoxiangCN** [comment] 2024-02-28 06:53
any updates? this reproduce in tikv6.5, which include [ raftstore: split raft write batch on 1GiB limit](https://github.com/tikv/tikv/pull/13872)

`
[FATAL] [lib.rs:495] 
["called `Result::unwrap()` on an `Err` value: Other(\"[components/raft_log_engine/src/engine.rs:646]: Full\")"]
 [backtrace="   
 0: tikv_util::set_panic_hook::{{closure}}\n   
 1: std::panicking::rust_panic_with_hook\n   
 2: std::panicking::begin_panic_handler::{{closure}}\n   
 3: std::sys_common::backtrace::__rust_end_short_backtrace\n   
 4: rust_begin_unwind\n   
 5: core::panicking::panic_fmt\n   
 6: core::result::unwrap_failed\n   
 7: raftstore::store::async_io::write::WriteTaskBatch<EK,ER>::add_write_task\n   
 8: raftstore::store::async_io::write::Worker<EK,ER,N,T>::handle_msg\n   
 9: raftstore::store::async_io::write::Worker<EK,ER,N,T>::run\n  
 10: std::sys_common::backtrace::__rust_begin_short_backtrace\n  
 11: core::ops::function::FnOnce::call_once{{vtable.shim}}\n  
 12: std::sys::unix::thread::Thread::new::thread_start\n  
 13: start_thread\n  
 14: __clone\n"] [location=/data/tikv/components/raftstore/src/store/async_io/write.rs:449] 
[thread_name=store-writer-0]
`
