### ISSUE TITLE
reigon is unavailable: one tikv server does not accept new connections

### ISSUE THREAD

**Issue by cosven** [tikv/tikv#8987] opened 2020-11-06 06:42 UTC
## Bug Report

I met "region is unavailable" error on the client side. The problem last for several hours until I restart one abnormal tikv instance.

* the abnormal tikv does not accept new connections (I use `nc 127.0.0.1 20160` to check）
    connecting to the abnormal tikv gave no output (which illustrated that the tikv server is alive but it can't establish a connection)
    ```
    nc 127.0.0.1 20160
    ^Cpunt!
    ```
    connecting to the normal tikv should output like this
    ```
    nc 127.0.0.1 20160
    @@^Cpunt!
    ```
* too many CLOSE_WAIT on the abnormal tikv (use `netstat | grep CLOSE_WAIT`)

### What version of TiKV are you using?

```
TiKV
Release Version:   4.1.0-alpha
Edition:           Community
Git Commit Hash:   d39b582aa359bef1d9e2dae96ac3c5aced4144b5
Git Commit Branch: master
UTC Build Time:    2020-11-05 09:27:36
Rust Version:      rustc 1.49.0-nightly (b1496c6e6 2020-10-18)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb
Profile:           dist_release
```

### Steps to reproduce

run [tipocket bank2 testcase](https://github.com/pingcap/tipocket/blob/master/cmd/bank2/main.go) for about 2 hours

### What did you expect?

There should be no abnormal tikv instance.

### What did happened?

 I did some investigation and found that
* I usesd the `netcat` and `ping` command to check the network between tikv instances and it is ok
* one of the tikv server does not accept new connections (I use `nc 127.0.0.1 20160` to check）
    the abnormal tikv
    ```
    nc 127.0.0.1 20160
    ^Cpunt!
    ```
    the normal tikv
    ```
    nc 127.0.0.1 20160
    @@^Cpunt!
    ```
* too many CLOSE_WAIT on the abnormal tikv (use `netstat | grep CLOSE_WAIT`)
    ```
    netstat | grep CLOSE_WAIT|wc -l
    405
    ```

tail of the abnormal tikv log
```
[2020/11/06 06:15:36.757 +00:00] [WARN] [peer.rs:3138] ["failed to send msg to other peer"] [error_code=KV:Raftstore:Transport] [err=Transport(Full)] [target_store_id=5] [target_peer_id=1587] [peer_id=1605] [region_id=517]
[2020/11/06 06:15:37.444 +00:00] [INFO] [raft.rs:1357] ["starting a new election"] [term=699] [raft_id=1600] [region_id=372]
[2020/11/06 06:15:37.444 +00:00] [INFO] [raft.rs:1007] ["became pre-candidate at term 699"] [term=699] [raft_id=1600] [region_id=372]
[2020/11/06 06:15:37.444 +00:00] [INFO] [raft.rs:1115] ["broadcasting vote request"] [to="[1195, 1550]"] [log_index=137003] [log_term=699] [term=699] [type=MsgRequestPreVote] [raft_id=1600] [region_id=372]
[2020/11/06 06:15:37.444 +00:00] [WARN] [peer.rs:3138] ["failed to send msg to other peer"] [error_code=KV:Raftstore:Transport] [err=Transport(Full)] [target_store_id=5] [target_peer_id=1195] [peer_id=1600] [region_id=372]
[2020/11/06 06:15:37.444 +00:00] [WARN] [peer.rs:3138] ["failed to send msg to other peer"] [error_code=KV:Raftstore:Transport] [err=Transport(Full)] [target_store_id=1] [target_peer_id=1550] [peer_id=1600] [region_id=372]
[2020/11/06 06:15:38.361 +00:00] [INFO] [raft.rs:1357] ["starting a new election"] [term=567] [raft_id=1618] [region_id=506]
[2020/11/06 06:15:38.361 +00:00] [INFO] [raft.rs:1007] ["became pre-candidate at term 567"] [term=567] [raft_id=1618] [region_id=506]
[2020/11/06 06:15:38.361 +00:00] [INFO] [raft.rs:1115] ["broadcasting vote request"] [to="[1033, 582]"] [log_index=118769] [log_term=567] [term=567] [type=MsgRequestPreVote] [raft_id=1618] [region_id=506]
[2020/11/06 06:15:38.361 +00:00] [WARN] [peer.rs:3138] ["failed to send msg to other peer"] [error_code=KV:Raftstore:Transport] [err=Transport(Full)] [target_store_id=5] [target_peer_id=1033] [peer_id=1618] [region_id=506]
[2020/11/06 06:15:38.361 +00:00] [WARN] [peer.rs:3138] ["failed to send msg to other peer"] [error_code=KV:Raftstore:Transport] [err=Transport(Full)] [target_store_id=1] [target_peer_id=582] [peer_id=1618] [region_id=506]
```

**Comment by hicqu** [comment] 2020-11-06 09:34
Fixed by https://github.com/tikv/tikv/pull/8971.

**Comment by cosven** [comment] 2020-11-06 09:44
I'll run the bank2 test with latest tikv.

**Comment by cosven** [comment] 2020-11-09 06:39
reproduced with latest version 7eb58846e48c4eb68830f39870e2a303f969df32
```sh
/ # netstat | head -n 20 | grep CLOSE_WAIT
tcp       53      0 10.244.0.83:20160       10.244.3.116:55618      CLOSE_WAIT
tcp       53      0 10.244.0.83:20160       10.244.0.84:57516       CLOSE_WAIT
tcp       53      0 10.244.0.83:20160       10.244.3.116:51246      CLOSE_WAIT
tcp       53      0 10.244.0.83:20160       10.244.0.84:50726       CLOSE_WAIT
tcp       53      0 10.244.0.83:20160       10.244.3.116:59400      CLOSE_WAIT
tcp       53      0 10.244.0.83:20160       10.244.0.84:52970       CLOSE_WAIT
tcp       53      0 10.244.0.83:20160       10.244.0.84:53782       CLOSE_WAIT
tcp       53      0 10.244.0.83:20160       10.244.3.116:51196      CLOSE_WAIT
tcp       53      0 10.244.0.83:20160       10.244.0.84:51842       CLOSE_WAIT
tcp       53      0 10.244.0.83:20160       10.244.0.84:55548       CLOSE_WAIT
tcp       53      0 10.244.0.83:20160       10.244.3.116:55324      CLOSE_WAIT
tcp       53      0 10.244.0.83:20160       10.244.0.84:53952       CLOSE_WAIT
tcp       53      0 10.244.0.83:20160       10.244.3.116:56100      CLOSE_WAIT
tcp       53      0 10.244.0.83:20160       10.244.3.116:53430      CLOSE_WAIT
tcp       53      0 10.244.0.83:20160       10.244.3.116:56748      CLOSE_WAIT
tcp     1509      0 10.244.0.83:20160       10.244.0.82:49938       CLOSE_WAIT
tcp       53      0 10.244.0.83:20160       10.244.0.84:55444       CLOSE_WAIT
tcp       53      0 10.244.0.83:20160       10.244.3.116:48060      CLOSE_WAIT
/ # nc 127.0.0.1 20160
^Cpunt!

/ # /tikv-server -V
TiKV
Release Version:   4.1.0-alpha
Edition:           Community
Git Commit Hash:   7eb58846e48c4eb68830f39870e2a303f969df32
Git Commit Branch: master
UTC Build Time:    2020-11-08 01:35:31
Rust Version:      rustc 1.49.0-nightly (b1496c6e6 2020-10-18)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb
Profile:           dist_release
/ #
```

**Comment by hicqu** [comment] 2020-11-11 10:56
Test it again we found that raftstore threads are blocked:
```
Thread 48 (LWP 90):
#0  0x00007f9977f888dc in pthread_cond_wait () from /usr/glibc-compat/lib/libpthread.so.0
#1  0x000055e8bfb2b17d in rocksdb::port::CondVar::Wait (this=this@entry=0x7f997712d758) at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/c6b58a4/librocksdb_sys/rocksdb/port/port_posix.cc:106
#2  0x000055e8bfa63929 in rocksdb::WriteThread::LinkOne (this=this@entry=0x7f997712d580, w=w@entry=0x7f992b9d76d0, newest_writer=newest_writer@entry=0x7f997712d618) at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/c6b58a4/librocksdb_sys/rocksdb/db/write_thread.cc:269
#3  0x000055e8bfa63d99 in rocksdb::WriteThread::JoinBatchGroup (this=this@entry=0x7f997712d580, w=w@entry=0x7f992b9d76d0) at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/c6b58a4/librocksdb_sys/rocksdb/db/write_thread.cc:396
#4  0x000055e8bf9a6be5 in rocksdb::DBImpl::MultiBatchWriteImpl (this=this@entry=0x7f997712cc00, write_options=..., my_batch=..., callback=callback@entry=0x0, log_used=log_used@entry=0x0, log_ref=log_ref@entry=0, seq_used=seq_used@entry=0x0) at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/c6b58a4/librocksdb_sys/rocksdb/db/db_impl/db_impl_write.cc:86
#5  0x000055e8bf9aafa0 in rocksdb::DBImpl::WriteImpl (this=0x7f997712cc00, write_options=..., my_batch=0x7f9977623560, callback=callback@entry=0x0, log_used=log_used@entry=0x0, log_ref=log_ref@entry=0, disable_memtable=disable_memtable@entry=false, seq_used=seq_used@entry=0x0, batch_cnt=batch_cnt@entry=0, pre_release_callback=pre_release_callback@entry=0x0) at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/c6b58a4/librocksdb_sys/rocksdb/db/db_impl/db_impl_write.cc:326
#6  0x000055e8bf9acb32 in rocksdb::DBImpl::Write (this=<optimized out>, write_options=..., my_batch=<optimized out>) at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/c6b58a4/librocksdb_sys/rocksdb/db/db_impl/db_impl_write.cc:58
#7  0x000055e8bfb3b90b in rocksdb::titandb::TitanDBImpl::Write (this=0x7f99777d9000, options=..., updates=<optimized out>) at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/c6b58a4/librocksdb_sys/libtitan_sys/titan/src/db_impl.cc:568
#8  0x000055e8bf8cea6a in crocksdb_write (db=<optimized out>, options=<optimized out>, batch=<optimized out>, errptr=0x7f992b9d81f0) at crocksdb/c.cc:1040
#9  0x000055e8be8fac39 in batch_system::batch::Poller<N,C,Handler>::poll (self=<optimized out>) at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/c6b58a4/src/rocksdb.rs:790
#10 0x000055e8be8f6ff6 in std::sys_common::backtrace::__rust_begin_short_backtrace (f=...) at /home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/components/batch-system/src/batch.rs:396
#11 0x000055e8be8f6e9c in core::ops::function::FnOnce::call_once{{vtable-shim}} () at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/thread/mod.rs:470
#12 0x000055e8bf172a3a in std::sys::unix::thread::Thread::new::thread_start () at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/alloc/src/boxed.rs:1042
#13 0x00007f9977f81f30 in ?? () from /usr/glibc-compat/lib/libpthread.so.0
#14 0x00007f9977d4b27f in clone () from /usr/glibc-compat/lib/libc.so.6
```

```
Thread 49 (LWP 91):
#0  0x00007f9977f888dc in pthread_cond_wait () from /usr/glibc-compat/lib/libpthread.so.0
#1  0x000055e8bfb2b17d in rocksdb::port::CondVar::Wait (this=this@entry=0x7f997712d758) at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/c6b58a4/librocksdb_sys/rocksdb/port/port_posix.cc:106
#2  0x000055e8bfa63929 in rocksdb::WriteThread::LinkOne (this=this@entry=0x7f997712d580, w=w@entry=0x7f992b7d66d0, newest_writer=newest_writer@entry=0x7f997712d618) at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/c6b58a4/librocksdb_sys/rocksdb/db/write_thread.cc:269
#3  0x000055e8bfa63d99 in rocksdb::WriteThread::JoinBatchGroup (this=this@entry=0x7f997712d580, w=w@entry=0x7f992b7d66d0) at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/c6b58a4/librocksdb_sys/rocksdb/db/write_thread.cc:396
#4  0x000055e8bf9a6be5 in rocksdb::DBImpl::MultiBatchWriteImpl (this=this@entry=0x7f997712cc00, write_options=..., my_batch=..., callback=callback@entry=0x0, log_used=log_used@entry=0x0, log_ref=log_ref@entry=0, seq_used=seq_used@entry=0x0) at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/c6b58a4/librocksdb_sys/rocksdb/db/db_impl/db_impl_write.cc:86
#5  0x000055e8bf9aafa0 in rocksdb::DBImpl::WriteImpl (this=0x7f997712cc00, write_options=..., my_batch=0x7f99771067d0, callback=callback@entry=0x0, log_used=log_used@entry=0x0, log_ref=log_ref@entry=0, disable_memtable=disable_memtable@entry=false, seq_used=seq_used@entry=0x0, batch_cnt=batch_cnt@entry=0, pre_release_callback=pre_release_callback@entry=0x0) at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/c6b58a4/librocksdb_sys/rocksdb/db/db_impl/db_impl_write.cc:326
#6  0x000055e8bf9acb32 in rocksdb::DBImpl::Write (this=<optimized out>, write_options=..., my_batch=<optimized out>) at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/c6b58a4/librocksdb_sys/rocksdb/db/db_impl/db_impl_write.cc:58
#7  0x000055e8bfb3b90b in rocksdb::titandb::TitanDBImpl::Write (this=0x7f99777d9000, options=..., updates=<optimized out>) at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/c6b58a4/librocksdb_sys/libtitan_sys/titan/src/db_impl.cc:568
#8  0x000055e8bf8cea6a in crocksdb_write (db=<optimized out>, options=<optimized out>, batch=<optimized out>, errptr=0x7f992b7d71f0) at crocksdb/c.cc:1040
#9  0x000055e8be8fac39 in batch_system::batch::Poller<N,C,Handler>::poll (self=<optimized out>) at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/c6b58a4/src/rocksdb.rs:790
#10 0x000055e8be8f6ff6 in std::sys_common::backtrace::__rust_begin_short_backtrace (f=...) at /home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/components/batch-system/src/batch.rs:396
#11 0x000055e8be8f6e9c in core::ops::function::FnOnce::call_once{{vtable-shim}} () at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/thread/mod.rs:470
#12 0x000055e8bf172a3a in std::sys::unix::thread::Thread::new::thread_start () at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/alloc/src/boxed.rs:1042
#13 0x00007f9977f81f30 in ?? () from /usr/glibc-compat/lib/libpthread.so.0
#14 0x00007f9977d4b27f in clone () from /usr/glibc-compat/lib/libc.so.6
```

**Comment by hicqu** [comment] 2020-11-12 06:04
Test it again, seems grpc threads are blocked:
```
        Thread 80 (LWP 9420):
#0  0x00007f580aeb48dc in pthread_cond_wait () from target:/usr/glibc-compat/lib/libpthread.so.0
#1  0x0000564974dd3292 in gpr_cv_wait (cv=0x7f580a7c04d0, mu=0x7f580a7c0498, abs_deadline=...) at
        /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.6.0/grpc/src/core/lib/gpr/sync_posix.cc:130
#2  0x0000564974e9ab8f in grpc_core::Executor::ThreadMain (arg=0x7f580a7c0498) at /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.6.0/grpc/src/core/lib/iomgr/executor.cc:231
#3  0x0000564974dff98c in grpc_core::(anonymous namespace)::ThreadInternalsPosix::__lambda0::operator() (__closure=0x0, v=<optimized out>)
            at /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.6.0/grpc/src/core/lib/gprpp/thd_posix.cc:140
#4  grpc_core::(anonymous namespace)::ThreadInternalsPosix::__lambda0::_FUN (v=<optimized out>) at
            /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.6.0/grpc/src/core/lib/gprpp/thd_posix.cc:145
#5  0x00007f580aeadf30 in ?? () from target:/usr/glibc-compat/lib/libpthread.so.0
#6  0x00007f580ac7727f in clone () from target:/usr/glibc-compat/lib/libc.so.6

            Thread 79 (LWP 9419):
#0  0x00007f580aeb48dc in pthread_cond_wait () from target:/usr/glibc-compat/lib/libpthread.so.0
#1  0x0000564974dd3292 in gpr_cv_wait (cv=0x7f580a7c0428, mu=0x7f580a7c03f0, abs_deadline=...) at
            /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.6.0/grpc/src/core/lib/gpr/sync_posix.cc:130
#2  0x0000564974e9ab8f in grpc_core::Executor::ThreadMain (arg=0x7f580a7c03f0) at /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.6.0/grpc/src/core/lib/iomgr/executor.cc:231
#3  0x0000564974dff98c in grpc_core::(anonymous namespace)::ThreadInternalsPosix::__lambda0::operator() (__closure=0x0, v=<optimized out>)
                at /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.6.0/grpc/src/core/lib/gprpp/thd_posix.cc:140
#4  grpc_core::(anonymous namespace)::ThreadInternalsPosix::__lambda0::_FUN (v=<optimized out>) at
                /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.6.0/grpc/src/core/lib/gprpp/thd_posix.cc:145
#5  0x00007f580aeadf30 in ?? () from target:/usr/glibc-compat/lib/libpthread.so.0
#6  0x00007f580ac7727f in clone () from target:/usr/glibc-compat/lib/libc.so.6
```

**Comment by cosven** [comment] 2020-11-16 02:15
The root cause may be https://github.com/tikv/tikv/issues/9044

**Comment by 5kbpers** [comment] 2020-12-11 02:25
@cosven Should we close it since found the root cause?

**Closed** 2020-12-11 02:27 UTC
Labels: severity/major, type/bug
