### ISSUE TITLE
[Dynamic Regions] resolved ts blocked after region merge

### ISSUE THREAD

**Issue by seiya-annie** [tikv/tikv#15386] opened 2023-08-22 05:08 UTC
### What version of TiKV are you using?

[2023/08/15 03:03:02.893 +00:00] [INFO] [lib.rs:93] ["Git Commit Hash:   09239a7ca87b592f01454686bad1a084bd067546"]
### Steps to reproduce

execute flashback during pitr
### What did you expect?
pitr run normally ,flashback run normally
### What did happened?
```
2023-08-15T06:41:35.501Z        FATAL   ./main.go:119   Br PiTR FLASHBACK DDL Comp failed       {"error": "Error 1105: cannot set flashback
 timestamp after min-resolved-ts(2023-08-15 04:20:59.992 +0000 UTC)", "errorVerbose": "Error 1105: cannot set flashback timestamp after min
-resolved-ts(2023-08-15 04:20:59.992 +0000 UTC)\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9
687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.Trace\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/juju_adaptor.
go:15\ngithub.com/pingcap/test-infra/caselib/pkg/steps.(*executeSqlStatements).Execute\n\tgithub.com/pingcap/test-infra/caselib/pkg/steps/d
atabase.go:367\ngithub.com/pingcap/test-infra/caselib/pkg/steps.(*Serial).Execute\n\tgithub.com/pingcap/test-infra/caselib/pkg/steps/step.g
o:31\nmain.main\n\t./main.go:118\nruntime.main\n\truntime/proc.go:250\nruntime.goexit\n\truntime/asm_amd64.s:1594"}
main.main
```

**Comment by seiya-annie** [comment] 2023-08-22 05:14
[tikv0.log.gz](https://github.com/tikv/tikv/files/12404992/tikv0.log.gz)

**Comment by seiya-annie** [comment] 2023-08-22 05:14
[tikv1.log.gz](https://github.com/tikv/tikv/files/12405004/tikv1.log.gz)

**Comment by seiya-annie** [comment] 2023-08-22 05:15
[tikv2.log.gz](https://github.com/tikv/tikv/files/12405007/tikv2.log.gz)

**Comment by tonyxuqqi** [comment] 2023-08-24 13:40
It's likely dup with https://github.com/tikv/tikv/issues/15198

**Comment by tonyxuqqi** [comment] 2023-08-24 13:41
@seiya-annie  Please use latest master to verify. The merge issue should be fixed.

**Comment by overvenus** [comment] 2023-08-29 05:23
Duplicate of #15258

**Closed by overvenus** 2023-08-29 05:23 UTC
Labels: type/bug, severity/critical, feature/developing, may-affects-5.2, may-affects-5.3, may-affects-5.4, may-affects-6.1, may-affects-6.5, may-affects-7.1
