### ISSUE TITLE
[Dynamic Regions] stale read with raft-kv2 returns unexpected region error occasionally

### ISSUE THREAD

**Issue by crazycs520** [tikv/tikv#15748] opened 2023-10-11 09:10 UTC
## Bug Report

client-go maybe receive following error when send stale-read request.

```log
[2023/10/11 15:35:54.523 +08:00] [INFO] [region_request.go:1497] ["send request got region error"] [conn=3967811628] [session_alias=] [err-message="\"[components/raftstore-v2/src/operation/query/mod.rs:139]: PeerMsg::RaftQuery should not get stale read requests\""] [err-string="message:\"\\\"[components/raftstore-v2/src/operation/query/mod.rs:139]: PeerMsg::RaftQuery should not get stale read requests\\\"\" "]
```

### What version of TiKV are you using?

nightly: 58253e8b7cea59b414511753b75dd7fc980d99af

**Comment by glorv** [comment] 2023-10-13 07:26
https://github.com/tikv/tikv/blob/b4e0bf7bab6ad395b74c0be938119d82ded4cd2a/components/raftstore-v2/src/operation/query/local.rs#L315-L321

The root cause is if `try_get_snapshot` returns Redirect due to `ReadDelegate` is not exist, raft-v2 will always do `try_to_renew_lease` which will triggers a readIndex. This is not true for staleRead.

**Comment by zhangjinpeng87** [comment] 2024-04-23 02:33
Close this issue temporarily since Dynamic Regions project is paused.

**Closed by zhangjinpeng87** 2024-04-23 02:33 UTC
Labels: type/bug, severity/major, feature/developing, may-affects-5.3, may-affects-5.4, may-affects-6.1, may-affects-6.5, may-affects-7.1, may-affects-7.5, affects-8.1
