### ISSUE TITLE
After spliting regions, the size of the new regions are not updated to zero but None.

### ISSUE THREAD

**Issue by CabinfeverB** [tikv/tikv#15696] opened 2023-09-27 06:00 UTC
### What version of TiKV are you using?

master
### Steps to reproduce

See title

**Comment by tonyxuqqi** [comment] 2024-01-29 18:59
It may be related to https://github.com/tikv/tikv/pull/15456

**Comment by bufferflies** [comment] 2024-01-30 02:29
> It may be related to #15456

no, only the region size checker is busy. It can be closed by designed.

**Closed** 2024-05-22 08:47 UTC
Labels: type/bug, severity/major, may-affects-5.3, may-affects-5.4, may-affects-6.1, may-affects-6.5, may-affects-7.1, affects-7.5, affects-8.1
