### ISSUE TITLE
Enabling failpoint `raftkv_early_error_report`, `cleanup`, `pessimistic_prewrite` sometimes leads to tikv panic

### ISSUE THREAD

**Issue by seiya-annie** [tikv/tikv#15020] opened 2023-06-27 10:01 UTC
### What version of TiKV are you using?
sh-5.1# ./tikv-server -V
TiKV 
Release Version:   7.2.0
Edition:           Community
Git Commit Hash:   12ce5540f9e8f781f14d3b3a58fb9442f03b6b29
Git Commit Branch: heads/refs/tags/v7.2.0
UTC Build Time:    2023-06-19 09:16:29
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse failpoints test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
sh-5.1# 

### Steps to reproduce

Run [`SkipLockRead`](https://github.com/PingCAP-QE/automated-tests/blob/66d637144b626916cad42cd27e32f322e7660fcd/ticases/transaction/pessimistic/cases.go#L1050) which is a test case in UTF.

One of the subcase in `SkipLockRead` will encounter this problem. The subcase sets following failpoints of TiKV. It's not sure yet which is the one that causes the problem:

* `raftkv_early_error_report` = `return(?)` where `?` is some region ID that's being accessed
* `cleanup` = `return(other)`
* `pessimistic_rollback` = `return(PessimisticLockNotFound)`

### What did you expect?

The test case executes successfully

### What did happened?

TiKV panicked:

```
[2023/06/26 17:18:06.454 +00:00] [FATAL] [lib.rs:497] ["undetermined error: Error(Undetermined(\"async write on_applied callback is dropped\")) cid=2737, tag=pessimistic_rollback, process\n                        result=Some(MultiRes { results: [] })"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:496:18\n   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2032:9\n      std::panicking::rust_panic_with_hook\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:692:13\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:579:13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137:18\n   4: rust_begin_unwind\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:575:5\n   5: core::panicking::panic_fmt\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:65:14\n   6: tikv::storage::txn::scheduler::TxnScheduler<E,L>::on_write_finished\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/src/storage/txn/scheduler.rs:845:25\n   7: tikv::storage::txn::scheduler::TxnScheduler<E,L>::process_write::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/src/storage/txn/scheduler.rs:1597:21\n   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:91:19\n      tikv::storage::txn::scheduler::TxnScheduler<E,L>::process::{{closure}}::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/src/storage/txn/scheduler.rs:1152:71\n      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:91:19\n      <resource_metering::InTags<T> as core::future::future::Future>::poll\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/resource_metering/src/lib.rs:266:9\n      tikv::storage::txn::scheduler::TxnScheduler<E,L>::process::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/src/storage/txn/scheduler.rs:1166:9\n      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:91:19\n      tikv::storage::txn::scheduler::TxnScheduler<E,L>::execute::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/src/storage/txn/scheduler.rs:735:54\n   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:91:19\n      <tracker::tls::TrackedFuture<F> as core::future::future::Future>::poll::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tracker/src/tls.rs:64:23\n      std::thread::local::LocalKey<T>::try_with\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:446:16\n      std::thread::local::LocalKey<T>::with\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:422:9\n      <tracker::tls::TrackedFuture<F> as core::future::future::Future>::poll\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tracker/src/tls.rs:62:9\n      tikv_util::yatp_pool::future_pool::PoolInner::spawn::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/future_pool.rs:167:27\n      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:91:19\n      yatp::task::future::RawTask<F>::poll\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5523a9a/src/task/future.rs:59:9\n  10: yatp::task::future::TaskCell::poll\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5523a9a/src/task/future.rs:103:9\n      <yatp::task::future::Runner as yatp::pool::runner::Runner>::handle\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5523a9a/src/task/future.rs:387:20\n  11: <tikv_util::yatp_pool::YatpPoolRunner<T> as yatp::pool::runner::Runner>::handle\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/mod.rs:193:24\n  12: yatp::pool::worker::WorkerThread<T,R>::run\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5523a9a/src/pool/worker.rs:48:13\n      yatp::pool::builder::LazyBuilder<T>::build::{{closure}}\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5523a9a/src/pool/builder.rs:114:25\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:121:18\n  13: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:551:17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:271:9\n      std::panicking::try::do_call\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:483:40\n      std::panicking::try\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:447:19\n      std::panic::catch_unwind\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:550:30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:513:5\n  14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9\n      std::sys::unix::thread::Thread::new::thread_start\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17\n  15: start_thread\n  16: __GI___clone\n"] [location=/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/src/storage/txn/scheduler.rs:845] [thread_name=sched-worker-pool-3]
```

And the test case failed:

```
Error:
        Error Trace:    cases.go:1376
                                                sql.go:62
                                                cases.go:1342
                                                util.go:85
                                                case.go:28
                                                runner.go:134
                                                command.go:228
                                                command.go:840
                                                command.go:945
                                                command.go:885
                                                main.go:27
                                                proc.go:250
                                                asm_amd64.s:1571
        Error:          An error is expected but got nil.
```

which is thrown at:

https://github.com/PingCAP-QE/automated-tests/blob/66d637144b626916cad42cd27e32f322e7660fcd/ticases/transaction/pessimistic/cases.go#L1376

**Comment by seiya-annie** [comment] 2023-06-27 10:02
[tikv.log.gz](https://github.com/tikv/tikv/files/11880553/tikv.log.gz)

**Comment by cfzjywxk** [comment] 2023-06-27 13:44
If the cause is the incompatibility between newly added assertions and previous test cases, we should open an issue in the test case repository recording the necessity of refactoring the cases as needed.

**Comment by MyonKeminta** [comment] 2023-06-29 08:58
The cause is that [`async_write`](https://github.com/tikv/tikv/blob/fa7baa9a5ab38a2c0872ec772252bf16158f6fb5/src/server/raftkv/mod.rs#L453) didn't use `on_applied` callback (which we wrapped with `must_call` recently) when the local variable `res` is an `Err`. `res` is made in the following code:

```rust
 let mut res = (|| {
            fail_point!("raftkv_async_write");
            if batch.modifies.is_empty() {
                return Err(KvError::from(KvErrorInner::EmptyRequest));
            }
            Ok(())
        })();

        ASYNC_REQUESTS_COUNTER_VEC.write.all.inc();
        let begin_instant = Instant::now_coarse();

        if res.is_ok() {
            // If rid is some, only the specified region reports error.
            // If rid is None, all regions report error.
            res = (|| {
                fail_point!("raftkv_early_error_report", |rid| {
                    let region_id = ctx.get_region_id();
                    rid.and_then(|rid| {
                        let rid: u64 = rid.parse().unwrap();
                        if rid == region_id { None } else { Some(()) }
                    })
                    .ok_or_else(|| RaftServerError::RegionNotFound(region_id).into())
                });
                Ok(())
            })();
        }
```

It's possible to be `Err` only when:

* An empty write batch is passed to `async_write`, which should be unreachable in fact; or
* Failpoint `raftkv_early_error_report` is enabled to make a mock error.

To fix the problem, it seems that we can just call the callback when `res` is an error at:

https://github.com/tikv/tikv/blob/fa7baa9a5ab38a2c0872ec772252bf16158f6fb5/src/server/raftkv/mod.rs#L552

By the way, it's kind of weird that our CI didn't find this problem as there are tests that are making use of the failpoint `raftkv_early_error_report`. Are they not running on CI?

**Comment by MyonKeminta** [comment] 2023-06-29 09:00
Since async write won't be called with empty write batch in production, neigher will failpoints be used, this bug doesn't block releasing.

**Comment by cfzjywxk** [comment] 2023-06-29 12:05
> it seems that we can just call the callback when res  is an error

It's better to unify how the request is finished.

> Are they not running on CI?

There is  a test case `test_raftkv_early_error_report` using this failpoint, but it does not panic which is weird.

**Comment by MyonKeminta** [comment] 2023-07-07 05:19
https://github.com/tikv/tikv/pull/14872 's cherry-pick to 6.5 and 7.1 branch is not merged yet, and the problem would be introduced after merging them. Added affect-6.5 and affect-7.1 label for this issue.

**Closed** 2023-07-07 05:58 UTC
Labels: type/bug, severity/moderate, affects-6.5, affects-7.1, affects-7.2
