### ISSUE TITLE
Add learner operator runs very slow when hibernate region is on

### ISSUE THREAD

**Issue by MyonKeminta** [tikv/tikv#9681] opened 2021-02-20 10:01 UTC
### What version of TiKV are you using?

master (5.0.0-rc.x, 2d3c66cc44ea19a4e339ec44cf1fcd1477555b7d)

### What operating system and CPU are you using?

CentOS 7.6.1810

### Steps to reproduce

(I'm currently not sure if it can be reproduced)

Construct a case where a lot of region scheduling or adding peer. For example:

1. Prepare a cluster with at least 4 TiKV nodes and load a lot of data to generate 10K+ regions. Enable hibernate region.
2. Stop all read and write, and then all regions should be cold.
3. Stop one of the nodes, and offline it with PD

### What did you expect?

The regions that has a missing peer should quickly add a new peer, limited by PD's configurations like region-schedule-limit, max-snapshot-count and store limit.

### What did happened?

It's slow. PD's metrics shows that AddLearner operator runs slowly. After disabling hibernate region, it becomes faster.
![image](https://user-images.githubusercontent.com/9948422/108591818-91550b80-73a5-11eb-874f-2b502624be9f.png)

**Comment by MyonKeminta** [comment] 2021-02-20 10:01
cc @BusyJay

**Comment by MyonKeminta** [comment] 2021-02-22 03:26
Ah, I forgot that I in the above example, when disabling hibernate region, store pool size is increased from 2 to 6. However the raftstore CPU usage is always low.
![image](https://user-images.githubusercontent.com/9948422/108653152-b8742000-7500-11eb-862c-8d47a39247e6.png)

**Comment by hicqu** [comment] 2021-03-18 04:06
Can't reproduce with my environment: 4 TiKV, store-pool-size = 2, hibernate_regions = true:
![图片](https://user-images.githubusercontent.com/8407317/111571774-4a123d00-87e2-11eb-83a3-b716f7fa2b97.png)

**Comment by BusyJay** [comment] 2021-03-18 04:27
I think it's probably related to slow heartbeat processing. /cc @HunDunDM Is it fixed in master or 5.0?

**Comment by HunDunDM** [comment] 2021-03-18 05:36
It has been fixed on `master` / `release-5.0` / `release-4.0`. We need to test whether this problem is solved at the same time.

**Comment by BusyJay** [comment] 2021-12-29 13:21
Closed due to not reproduced.

**Closed by BusyJay** 2021-12-29 13:21 UTC
Labels: type/bug, sig/raft, severity/major
