### ISSUE TITLE
[Dynamic Regions] panic with "region corrupted"

### ISSUE THREAD

**Issue by seiya-annie** [tikv/tikv#15242] opened 2023-07-28 09:21 UTC
### What version of TiKV are you using?
[2023/07/28 02:40:39.413 +00:00] [INFO] [lib.rs:93] ["Git Commit Hash:   0ad33d428e85cb59d7381f791f47428713ce16e5"]

### What did happened?
```
[2023/07/28 02:42:38.592 +00:00] [FATAL] [lib.rs:510] ["[peer_id=3906] [region_id=3905] region corrupted"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:509:18\n   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2032:9\n      std::panicking::rust_panic_with_hook\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:692:13\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:579:13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137:18\n   4: rust_begin_unwind\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:575:5\n   5: core::panicking::panic_fmt\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:65:14\n   6: raftstore_v2::fsm::store::StoreMeta<EK>::set_region\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore-v2/src/fsm/store.rs:77:13\n   7: raftstore_v2::operation::command::admin::merge::commit::<impl raftstore_v2::raft::peer::Peer<EK,ER>>::on_apply_res_commit_merge\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/admin/merge/commit.rs:749:13\n      raftstore_v2::operation::command::<impl raftstore_v2::raft::peer::Peer<EK,ER>>::on_apply_res\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/mod.rs:427:53\n   8: raftstore_v2::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_msgs\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore-v2/src/fsm/peer.rs:271:43\n   9: <raftstore_v2::batch::store::StorePoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore_v2::fsm::peer::PeerFsm<EK,ER>,raftstore_v2::fsm::store::StoreFsm>>::handle_normal\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore-v2/src/batch/store.rs:282:9\n      batch_system::batch::Poller<N,C,Handler>::poll\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:380:27\n  10: raftstore_v2::worker::refresh_config::PoolController<N,C,H>::increase_by::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore-v2/src/worker/refresh_config.rs:75:21\n      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:438:13\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:121:18\n  11: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:551:17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:271:9\n      std::panicking::try::do_call\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:483:40\n      std::panicking::try\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:447:19\n      std::panic::catch_unwind\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:550:30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:513:5\n  12: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9\n      std::sys::unix::thread::Thread::new::thread_start\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17\n  13: start_thread\n  14: clone\n"] [location=/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore-v2/src/fsm/store.rs:77] [thread_name=rs-1-0]

```

**Comment by seiya-annie** [comment] 2023-07-28 09:22
[kv.log](https://github.com/tikv/tikv/files/12192590/kv.log)

**Comment by seiya-annie** [comment] 2023-09-08 09:00
this issue is still exist in master

**Comment by tabokie** [comment] 2023-09-08 23:22
Nothing stands out in particular, we may need to log all calls to `set_region` to investigate this. cc @tonyxuqqi 
```
[2023/09/06 07:20:11.181 +00:00] [INFO] [region.rs:318] ["try to merge"] [merge="target { id: 11827 start_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3238FF3134373439FF373637FF31303635FF33000000FC000000FC end_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3238FF3134373439FF373637FF31303635FF34000000FC000000FC region_epoch { conf_ver: 239 version: 28 } peers { id: 11828 store_id: 6 } peers { id: 12617 store_id: 5 } peers { id: 12677 store_id: 4 } }"] [region_id=867]
[2023/09/06 07:20:11.181 +00:00] [INFO] [mod.rs:250] ["failed to propose admin command"] [error=PendingPrepareMerge] [cmd_type=PrepareMerge] [peer_id=10833] [region_id=867]
[2023/09/06 07:20:11.591 +00:00] [INFO] [transfer_leader.rs:211] ["transfer leader"] [peer="id: 11828 store_id: 6"] [peer_id=12617] [region_id=11827]
[2023/09/06 07:20:11.591 +00:00] [INFO] [raft.rs:1911] ["[term 11] starts to transfer leadership to 11828"] [lead_transferee=11828] [term=11] [raft_id=12617] [peer_id=12617] [region_id=11827]
[2023/09/06 07:20:11.591 +00:00] [INFO] [raft.rs:1924] ["sends MsgTimeoutNow to 11828 immediately as 11828 already has up-to-date log"] [lead_transferee=11828] [raft_id=12617] [peer_id=12617] [region_id=11827]
[2023/09/06 07:20:11.591 +00:00] [INFO] [prepare.rs:752] ["execute PrepareMerge"] [target_region="id: 11827 start_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3238FF3134373439FF373637FF31303635FF33000000FC000000FC end_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3238FF3134373439FF373637FF31303635FF34000000FC000000FC region_epoch { conf_ver: 239 version: 28 } peers { id: 11828 store_id: 6 } peers { id: 12617 store_id: 5 } peers { id: 12677 store_id: 4 }"] [index=206] [peer_id=10833] [region_id=867]
[2023/09/06 07:20:11.592 +00:00] [INFO] [tablet.rs:548] ["skipped flush memtable for follower"] [reason=unknown] [region_id=11827]
[2023/09/06 07:20:11.593 +00:00] [INFO] [mod.rs:270] ["Start pre flush tablet"] [reason=commit_merge] [target=11827] [peer_id=10833] [region_id=867]
[2023/09/06 07:20:11.593 +00:00] [INFO] [tablet.rs:519] ["skipped flush memtable for leader"] [reason=commit_merge] [region_id=11827]
[2023/09/06 07:20:11.593 +00:00] [INFO] [mod.rs:250] ["failed to propose admin command"] [error=Raft(ProposalDropped)] [cmd_type=CommitMerge] [peer_id=12617] [region_id=11827]
[2023/09/06 07:20:11.593 +00:00] [INFO] [endpoint.rs:447] ["register observe region"] [region="id: 867 start_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3238FF3134373439FF373637FF31303635FF34000000FC000000FC end_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3330FF0000000000FF000000F700000000FB region_epoch { conf_ver: 222 version: 29 } peers { id: 10833 store_id: 5 } peers { id: 12137 store_id: 4 } peers { id: 12837 store_id: 6 }"]
[2023/09/06 07:20:11.593 +00:00] [ERROR] [commit.rs:337] ["failed to propose commit merge"] [res="header { error { message: \"Raft raft: proposal dropped\" } current_term: 11 }"] [source=867] [peer_id=12617] [region_id=11827]
[2023/09/06 07:20:11.593 +00:00] [INFO] [compact_log.rs:344] ["record tombstone tablet"] [new_tablet_index=206] [prev_tablet_path=/opt/tidb/data/kv/tablets/merge-source_867_206] [peer_id=10833] [region_id=867]
[2023/09/06 07:20:11.593 +00:00] [INFO] [tablet.rs:548] ["skipped flush memtable for follower"] [reason=unknown] [region_id=11827]
[2023/09/06 07:20:11.601 +00:00] [INFO] [region.rs:318] ["try to merge"] [merge="target { id: 867 start_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3238FF3134373439FF373637FF31303635FF34000000FC000000FC end_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3330FF0000000000FF000000F700000000FB region_epoch { conf_ver: 222 version: 30 } peers { id: 10833 store_id: 5 } peers { id: 12137 store_id: 4 } peers { id: 12837 store_id: 6 } }"] [region_id=11827]
[2023/09/06 07:20:11.601 +00:00] [INFO] [mod.rs:250] ["failed to propose admin command"] [error=PendingPrepareMerge] [cmd_type=PrepareMerge] [peer_id=12617] [region_id=11827]
[2023/09/06 07:20:11.868 +00:00] [INFO] [raft.rs:1371] ["received a message with higher term from 11828"] ["msg type"=MsgRequestVote] [message_term=12] [term=11] [from=11828] [raft_id=12617] [peer_id=12617] [region_id=11827]
[2023/09/06 07:20:11.868 +00:00] [INFO] [raft.rs:1127] ["became follower at term 12"] [term=12] [raft_id=12617] [peer_id=12617] [region_id=11827]
[2023/09/06 07:20:11.868 +00:00] [INFO] [raft.rs:1572] ["[logterm: 11, index: 35, vote: 0] cast vote for 11828 [logterm: 11, index: 35] at term 12"] ["msg type"=MsgRequestVote] [term=12] [msg_index=35] [msg_term=11] [from=11828] [vote=0] [log_index=35] [log_term=11] [raft_id=12617] [peer_id=12617] [region_id=11827]
[2023/09/06 07:20:11.868 +00:00] [INFO] [endpoint.rs:529] ["deregister observe region"] [observe_id=ObserveId(3564)] [region_id=11827] [store_id=Some(5)]
[2023/09/06 07:20:12.013 +00:00] [INFO] [compact_log.rs:616] ["compact log"] [truncated="applied_index: 208 truncated_state { index: 207 term: 51 }"] [apply_trace="ApplyTrace { data_cfs: [Progress { flushed: 166, last_modified: 166 }, Progress { flushed: 166, last_modified: 166 }, Progress { flushed: 166, last_modified: 166 }], admin: Progress { flushed: 208, last_modified: 189 }, persisted_applied: 189, last_flush_trigger: 0, try_persist: false }"] [index=189] [peer_id=10833] [region_id=867]
[2023/09/06 07:20:12.421 +00:00] [INFO] [tablet.rs:548] ["skipped flush memtable for follower"] [reason=unknown] [region_id=11827]
[2023/09/06 07:20:12.464 +00:00] [INFO] [commit.rs:429] ["execute CommitMerge"] [source_region="id: 867 start_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3238FF3134373439FF373637FF31303635FF34000000FC000000FC end_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3330FF0000000000FF000000F700000000FB region_epoch { conf_ver: 222 version: 29 } peers { id: 10833 store_id: 5 } peers { id: 12137 store_id: 4 } peers { id: 12837 store_id: 6 }"] [index=37] [entries=1] [commit=206] [peer_id=12617] [region_id=11827]
[2023/09/06 07:20:12.492 +00:00] [INFO] [commit.rs:510] ["applied CommitMerge"] [flush=15ms] [merge=0s] [open=13ms] [wait=None] [source_region="id: 867 start_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3238FF3134373439FF373637FF31303635FF34000000FC000000FC end_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3330FF0000000000FF000000F700000000FB region_epoch { conf_ver: 222 version: 29 } peers { id: 10833 store_id: 5 } peers { id: 12137 store_id: 4 } peers { id: 12837 store_id: 6 }"] [peer_id=12617] [region_id=11827]
[2023/09/06 07:20:12.868 +00:00] [FATAL] [lib.rs:510] ["[peer_id=12617] [region_id=11827] region corrupted"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:509:18\n   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2032:9\n      std::panicking::rust_panic_with_hook\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:692:13\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:579:13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137:18\n   4: rust_begin_unwind\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:575:5\n   5: core::panicking::panic_fmt\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:65:14\n   6: raftstore_v2::fsm::store::StoreMeta<EK>::set_region\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore-v2/src/fsm/store.rs:77:13\n   7: raftstore_v2::operation::command::admin::merge::commit::<impl raftstore_v2::raft::peer::Peer<EK,ER>>::on_apply_res_commit_merge\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/admin/merge/commit.rs:749:13\n      raftstore_v2::operation::command::<impl raftstore_v2::raft::peer::Peer<EK,ER>>::on_apply_res\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/mod.rs:427:53\n   8: raftstore_v2::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_msgs\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore-v2/src/fsm/peer.rs:271:43\n   9: <raftstore_v2::batch::store::StorePoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore_v2::fsm::peer::PeerFsm<EK,ER>,raftstore_v2::fsm::store::StoreFsm>>::handle_normal\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore-v2/src/batch/store.rs:283:9\n      batch_system::batch::Poller<N,C,Handler>::poll\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:380:27\n  10: raftstore_v2::worker::refresh_config::PoolController<N,C,H>::increase_by::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore-v2/src/worker/refresh_config.rs:75:21\n      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:438:13\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:121:18\n  11: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:551:17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:271:9\n      std::panicking::try::do_call\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:483:40\n      std::panicking::try\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:447:19\n      std::panic::catch_unwind\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:550:30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:513:5\n  12: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9\n      std::sys::unix::thread::Thread::new::thread_start\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17\n  13: start_thread\n  14: clone\n"] [location=/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore-v2/src/fsm/store.rs:77] [thread_name=rs-5-1]
```

**Comment by SpadeA-Tang** [comment] 2023-09-20 02:42
This should be caused by the race conditition of concurrent execution between merge and transfer leader. https://github.com/tikv/tikv/pull/15625 uses integration test for reproduction (including the description of the steps) and fixed it.

Now, I close this issue. If it happen again,  reopen it.

**Closed by SpadeA-Tang** 2023-09-20 02:42 UTC
Labels: type/bug, severity/major, jepsen
