### ISSUE TITLE
Data inconsistency after flashback 

### ISSUE THREAD

**Issue by seiya-annie** [tikv/tikv#13672] opened 2022-10-25 09:51 UTC
### What version of TiKV are you using?
[root@localhost ~]# /data1/tidb-deploy/tikv-2360/bin/tikv-server -V
TiKV 
Release Version:   6.4.0-alpha
Edition:           Community
Git Commit Hash:   ed64ed21cfa1c734191549a0db66986dab04f4bd
Git Commit Branch: master
UTC Build Time:    2022-10-18 09:38:46
Rust Version:      rustc 1.64.0-nightly (0f4bcadb4 2022-07-30)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           release
[root@localhost ~]# 

### Steps to reproduce
install a tidb cluster with pitr task started
run workload for 10 minutes
flashback to 10 minutes ago
during flashback restart and stop/start tikv/pd/tidb
### What did happened?
MySQL [flashback2]> admin check table user_data1;
ERROR 8223 (HY000): data inconsistency in table: user_data1, index: k_1, handle: 22152, index-values:"" != record-values:"handle: 22152, values: [KindMysqlTime 2022-10-25 13:03:13]"
MySQL [flashback2]>

**Comment by seiya-annie** [comment] 2022-10-25 09:51
seem issue exist in flashback with cdc task

**Comment by JmPotato** [comment] 2022-10-26 05:44
This root cause is similar to https://github.com/tikv/tikv/issues/13643, since the TiKV may apply the split and prepare flashback cmd in the same batch without checking the epoch version, the newly split left region may be missed to execute the flashback. https://github.com/tikv/tikv/pull/13664 should fix this.

**Comment by JmPotato** [comment] 2022-10-28 09:52
A newly found bug will cause data inconsistency. Assume that a second phase procedure contains two batches to flashback. After the first batch is committed, if the region is down, it will retry the flashback from the very first beginning, because the data in the first batch has been written the flashbacked data with the same `commit_ts`, it will return directly due to these lines of code:

https://github.com/tikv/tikv/blob/fe61a03438d91bb1739e8e95db66c9927254d62f/src/storage/txn/actions/flashback_to_version.rs#L72-L78

This will leave the data in the second batch untouched to make the data become inconsistent after the flashback.

**Closed** 2022-11-04 02:16 UTC
Labels: type/bug, severity/major
