### ISSUE TITLE
15% performance regression on oltp_write_only of sysbench_pessimistic_small_data

### ISSUE THREAD

**Issue by mahjonp** [tikv/tikv#6345] opened 2019-12-26 12:16 UTC
## Bug Report

There is a 15%  performance regression on our sysbench_pessimistic_small_data benchmark test

1. What did you do?

Run performance test daily

2. What did you expect to see?

None.

3. What did you see instead?

```
Version:
    tidb: fcc5dba8a7d3b41458b5dc1a09992598cb6e8fb8(master) 2019-12-19 01:45:25
    tikv: 9295ab18eda9a83b074103bc4d515cf927566894(master) 2019-12-20 09:54:23
    pd: 4d65bbefbc6db6e92fee33caa97415274512757a(master) 2019-12-19 07:18:14
        
Compare:
    tidb: https://github.com/pingcap/tidb/compare/fcc5dba...fcc5dba
    tikv: https://github.com/tikv/tikv/compare/ae5cc1e...9295ab1
    pd: https://github.com/pingcap/pd/compare/4d65bbe...4d65bbe
        
test-1: < oltp_write_only >
    * QPS : 209.10 ± 0.1754% (std=0.30) delta: -15.64% (p=0.000)
    * TPS : 30.60 ± 0.0871% (std=0.02) delta: -11.29%
    * AvgMs : 4212.85 ± 0.1766% (std=6.02) delta: 13.05%
    * PercentileMs99 : 14052.25 ± 3.6333% (std=357.81) delta: -2.11%
```

4. What version of TiKV are you using?

see above: https://github.com/tikv/tikv/pull/6244

**Comment by mahjonp** [comment] 2019-12-27 02:26
Optimistic lock read_write benchmark was affected too.

![image](https://user-images.githubusercontent.com/3251373/71497417-0fe21600-2893-11ea-9c44-de60bb3b2317.png)

**Comment by youjiali1995** [comment] 2020-01-06 12:18
The regression is caused by deadlocks between waked up transactions and pending transactions.

There are lots of deadlocks in oltp_write_only with small tables:
![image](https://user-images.githubusercontent.com/14819777/71816586-13a94000-30be-11ea-90f0-bad7a6abbcb8.png)

I set different `wake-up-delay-duration` and the benchmark results are:

| wake-up-delay-duration(ms) | tps |
| ----- | ----- |
| 5 | 153.6 |
| 20 | 66.8 |
| 50 | 31.7 |
| 100(default) | 16|

In production, there won't be many deadlocks between these transactions. Nevertheless, I will decrease the default value.

**Comment by youjiali1995** [comment] 2020-01-08 06:51
I changed the default `wake-up-delay-duration` from 100ms to 20ms and the QPS has recovered so I will close it.
![image](https://user-images.githubusercontent.com/14819777/71956377-fc856200-3225-11ea-8e92-1c8f80459c66.png)
![image](https://user-images.githubusercontent.com/14819777/71956414-0f983200-3226-11ea-9fd8-5085e80c2afb.png)

**Comment by mahjonp** [comment] 2020-01-11 15:02
Although https://github.com/tikv/tikv/pull/6426 can fix this performance regression, it hurts the performance of bench_hotspot. 

```
 * QPS: 320.53(1.03x) ± 0.06% (std=0.13) delta: -18.32% (p=0.000)
    * Latency p50: 3797.63(0.99x) ± 0.12% (std=3.31) delta: 23.19%
    * Latency p99: 4733.41(0.98x) ± 1.20% (std=40.84) delta: 46.12%
```

**Closed** 2020-02-15 12:18 UTC
