### ISSUE TITLE
[Dynamic Regions] resolved ts blocked after region merge

### ISSUE THREAD

**Issue by seiya-annie** [tikv/tikv#15258] opened 2023-08-01 08:14 UTC
### What version of TiKV are you using?
[2023/07/30 04:15:22.889 +00:00] [INFO] [lib.rs:93] ["Git Commit Hash:   42882f8bcf4ce52ea93f93d325c000147ac2e137"]

### Steps to reproduce
execute flashback during pitr

### What did you expect?
pitr run normally ,flashback run normally
### What did happened?
2023-07-30T05:39:25.092Z        FATAL   ./main.go:125   Br PiTR DDL Comp failed {"error": "Error 1105: cannot set flashback timestamp aft
er min-resolved-ts(2023-07-30 05:23:03.204 +0000 UTC)", "errorVerbose": "Error 1105: cannot set flashback timestamp after min-resolved-ts
(2023-07-30 05:23:03.204 +0000 UTC)\[ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87](http://ngithub.com/pingcap/errors.AddStack/n/tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87)
c/errors.go:174\[ngithub.com/pingcap/errors.Trace\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/juju_adaptor.go:15\ng](http://ngithub.com/pingcap/errors.Trace/n/tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/juju_adaptor.go:15/ng)
[ithub.com/pingcap/test-infra/caselib/pkg/steps.(*executeSqlStatements).Execute\n\tgithub.com/pingcap/test-infra/caselib/pkg/steps/databas](http://ithub.com/pingcap/test-infra/caselib/pkg/steps.(*executeSqlStatements).Execute/n/tgithub.com/pingcap/test-infra/caselib/pkg/steps/databas)
e.go:367\[ngithub.com/pingcap/test-infra/caselib/pkg/steps.(*Parallel).Execute.func1\n\tgithub.com/pingcap/test-infra/caselib/pkg/steps/st](http://ngithub.com/pingcap/test-infra/caselib/pkg/steps.(*Parallel).Execute.func1/n/tgithub.com/pingcap/test-infra/caselib/pkg/steps/st)
ep.go:69\[ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75\nr](http://ngolang.org/x/sync/errgroup.(*Group).Go.func1/n/tgolang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75/nr)
untime.goexit\n\truntime/asm_amd64.s:1594"}

**Comment by seiya-annie** [comment] 2023-08-01 08:16
![20230801-161607](https://github.com/tikv/tikv/assets/53471087/f1db759e-3d5b-4a00-9cab-00e811a3ca73)

**Comment by seiya-annie** [comment] 2023-08-01 08:18
[tikv--0.log.gz](https://github.com/tikv/tikv/files/12226188/tikv--0.log.gz)

**Comment by seiya-annie** [comment] 2023-08-01 08:18
[tikv--1.log.gz](https://github.com/tikv/tikv/files/12226193/tikv--1.log.gz)

**Comment by seiya-annie** [comment] 2023-08-01 08:18
[tikv--2.log.gz](https://github.com/tikv/tikv/files/12226196/tikv--2.log.gz)

**Comment by overvenus** [comment] 2023-08-08 07:31
Root cause: PD does not consider flashback state changes when updating Region info. 

* Resolved TS is blocked because region merge is blocked.
* Region merged is blocked because Region info (flashback = true) on PD does not match TiKV local Region info (flashback = false), CommitMerge can not proceed.
* Region info (flashback = true) on PD because leader is changed during flashback.
* Region info does not update after flashback because PD does not consider flashback state change.

https://github.com/tikv/pd/blob/a605e11f984e35fa148c92387db52a1d178815bf/pkg/core/region.go#L672-L766

**Closed** 2023-08-10 09:52 UTC
Labels: type/bug, severity/major, affects-6.4, affects-6.5, affects-6.6, affects-7.0, affects-7.1, affects-7.2, affects-7.3
