### ISSUE TITLE
Flashback may break transaction atomicity

### ISSUE THREAD

**Issue by ekexium** [tikv/tikv#17415] opened 2024-08-22 12:00 UTC
### What version of TiKV are you using?

Any with Flashback.

### What operating system and CPU are you using?

Doesn't matter.

### Steps to reproduce

Consider the following sequence of events:

1. T1 starts, start_ts = 10
2. resolved_ts advances to 20.
3. T1 prewrites. lock_ts =10
4. T1 starts committing, commit_ts=30. PK committed, SK not yet
5. Flashback starts, flashback_ts = 19. It rolls back all locks, including the secondary locks of T1. Flashback finishes with commit_ts 40.
6. T1's atomicity is broken. E.g. a stale read at ts=35.

### What did you expect?

Transactions should be atomic.

### What did happened?

The stale read at step 6 can read the PK but cannot read the SK of T1.

**Comment by cfzjywxk** [comment] 2024-09-18 13:02
The flashback feature is now owned by the br team./cc @BornChanger

**Comment by YuJuncen** [comment] 2024-09-26 02:08
This is because we remove the lock directly but remove the commit record by putting a new mvcc version. We may need to use a resolve lock instead of remove all pending locks during flashback.

**Comment by YuJuncen** [comment] 2024-09-27 04:55
An unit test case (need real TiKV) to reproduce the issue:

<details><summary>Case</summary>

```go
func TestFlashbackStaleRead(t *testing.T) {
	if !*realtikvtest.WithRealTiKV {
		return
	}

	store := realtikvtest.CreateMockStoreAndSetup(t)
	kvStore := store.(tikv.Storage)
	tk := testkit.NewTestKit(t, store)

	timeBeforeDrop, _, safePointSQL, resetGC := MockGC(tk)
	defer resetGC()
	tk.MustExec(fmt.Sprintf(safePointSQL, timeBeforeDrop))
	tk.MustExec("use test")
	tk.MustExec("drop table if exists t")
	tk.MustExec("create table t(a int)")

	// KvPrewrite some rows.
	tableID, err := strconv.ParseInt(tk.MustQuery("select tidb_table_id from information_schema.tables where table_name = 't'").Rows()[0][0].(string), 10, 64)
	require.NoError(t, err)

	ctx := context.Background()
	mkMutation := func(handle int) *kvrpcpb.Mutation {
		require.LessOrEqual(t, handle, 0xff)
		// Constructing a row value requires too many context...
		hackyValue, err := hex.DecodeString(fmt.Sprintf("800001000000010100%02X", handle))
		require.NoError(t, err)
		return &kvrpcpb.Mutation{
			Op:    kvrpcpb.Op_Put,
			Key:   tablecodec.EncodeRowKeyWithHandle(tableID, kv.IntHandle(handle)),
			Value: hackyValue,
		}
	}

	rc := kvStore.GetRegionCache()
	bo := tikv.NewBackoffer(ctx, 5000)

	mkPrewrite := func(startTS uint64, handle int, pkHandle int) {
		req := &kvrpcpb.PrewriteRequest{
			Mutations:    []*kvrpcpb.Mutation{mkMutation(handle)},
			PrimaryLock:  tablecodec.EncodeRowKeyWithHandle(tableID, kv.IntHandle(pkHandle)),
			StartVersion: startTS,
			LockTtl:      4000,
		}
		loc, err := rc.LocateKey(bo, req.Mutations[0].Key)
		require.NoError(t, err)
		_, err = kvStore.SendReq(bo, tikvrpc.NewRequest(tikvrpc.CmdPrewrite, req), loc.Region, time.Second*10)
		require.NoError(t, err)

		fmt.Println("prewrite", startTS, handle, loc)
	}
	mkCommit := func(startTS uint64, commitTS uint64, pkHandle int, commitRegionOfHandle int) {
		require.NoError(t, err)
		loc, err := rc.LocateKey(bo, tablecodec.EncodeRowKeyWithHandle(tableID, kv.IntHandle(commitRegionOfHandle)))
		require.NoError(t, err)
		req := &kvrpcpb.CommitRequest{
			StartVersion:  startTS,
			Keys:          [][]byte{tablecodec.EncodeRowKeyWithHandle(tableID, kv.IntHandle(pkHandle))},
			CommitVersion: commitTS,
		}
		_, err = kvStore.SendReq(bo, tikvrpc.NewRequest(tikvrpc.CmdCommit, req), loc.Region, time.Second*10)
		require.NoError(t, err)

		fmt.Println("commit", commitTS, commitRegionOfHandle, loc)
	}
	allocateTs := func() uint64 {
		res, err := store.GetOracle().GetTimestamp(ctx, &oracle.Option{})
		require.NoError(t, err)
		return res
	}

	r := tk.MustQuery("split table t by (0), (43), (255)")
	fmt.Printf("%#v\n", r)

	time.Sleep(time.Second)
	startTS := allocateTs()
	mkPrewrite(startTS, 42, 42)
	mkPrewrite(startTS, 44, 42)
	time.Sleep(time.Second)
	commitTS := allocateTs()
	mkCommit(startTS, commitTS, 42, 42)
	time.Sleep(time.Second)

	tsoToSQL := func(ts uint64) string { return oracle.GetTimeFromTS(ts).Format(types.TimeFSPFormat) }
	injectSafeTS := oracle.GoTimeToTS(oracle.GetTimeFromTS(startTS - 1).Add(100 * time.Second))
	require.NoError(t, failpoint.Enable("github.com/pingcap/tidb/pkg/ddl/injectSafeTS",
		fmt.Sprintf("return(%v)", injectSafeTS)))
	tk.MustExec(fmt.Sprintf("flashback cluster to tso %d", startTS-1))

	res := tk.MustQuery(fmt.Sprintf("select * from t as of timestamp '%s'", tsoToSQL(commitTS+(10<<18))))
	require.Equal(t, len(res.Rows()), 2)
	require.Equal(t, res.Rows()[0][0], "42")
	require.Equal(t, res.Rows()[1][0], "44")
}
```

</details> 

This case failed with reading exact 1 record: atomicity broken.

![img_v3_02f3_254f462c-e29a-45f1-90bb-71b7d5c3968g](https://github.com/user-attachments/assets/9af8b590-fb21-4e27-967b-e612b86e1452)

**Comment by YuJuncen** [comment] 2024-09-27 05:10
But I must say it is pretty hard to encounter this problem in a production cluster, because this requires:

- TiDB failed to commit to a subset of regions (implies that TiDB was down?), and the lock not resolved until flashback triggered.
- We have flashed back to a version that greater than such a txn's commit ts (let it be `cts`).
- After `FLASHBACK  CLUSTER` done, we use stale read to read the time range between `cts` and the commit ts of `FLASHBACK CLUSTER`.

Fixing this bug requires either:
- Run resolve lock after `FLASHBACK CLUSTER` prepared and before it executed.
- Or, reject all snapshot read with ts lower than the commit ts of `FLASHBACK CLUSTER`.
Both of them cannot be easily implemented... The former requires resolve lock to bypass the restriction of flashback. The latter requires a system to manage such time ranges. 

Perhaps for now we'd better just document that "After flashback, stale less than `BEGIN; SELECT TIDB_CURRENT_TSO(); ABORT;` can read non-ACID results." Then we have enough time to discuss and implement this fix.

**Comment by overvenus** [comment] 2024-09-27 05:49
Cc https://github.com/tikv/tikv/issues/14531

**Comment by 3pointer** [comment] 2024-12-27 07:06
Considering the rarity of this scenario and the cost-benefit ratio of addressing it, we’ve decided to provide a clarification in the documentation: [PR #18903](https://github.com/pingcap/docs-cn/pull/18903). and make it `won't fix`.

**Closed by 3pointer** 2024-12-27 07:06 UTC
Labels: type/bug, component/backup-restore, severity/critical, may-affects-5.4, may-affects-6.1, may-affects-6.5, may-affects-7.1, may-affects-7.5, may-affects-8.1, affects-8.4, affects-8.5
