### ISSUE TITLE
[Dynamic Regions] tikv panic at "state: Merging region"

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#15642] opened 2023-09-20 03:53 UTC
### What version of TiKV are you using?
/tikv-server -V
 TiKV 
Release Version:   7.4.0-alpha
Edition:           Community
Git Commit Hash:   4a5fb7321ca2ee2bab0b31f6556c8fb196a590f4
Git Commit Branch: heads/refs/tags/v7.4.0-alpha
UTC Build Time:    2023-09-18 11:44:19
Rust Version:      rustc 1.73.0-nightly (180dffba1 2023-08-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2023-09-19T17:26:19.397+0800	

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
      cases:
        - name: "ha_tikv_random_kill"
          warmUpTime: 5m
          faultType: kill
          selector: "tikv(random)"
          period: "@every 10m"
          faultDuration: 1m
          faultTotalRunTime: 12h
          pdCommand : {
              "beforeCase": [ 'config set max-store-down-time 10m', 'schedule add shuffle-region-scheduler', 'schedule add shuffle-leader-scheduler', 'schedule add random-merge-scheduler' ],   
              "afterCase": [ 'config set max-store-down-time 30m', 'schedule remove shuffle-region-scheduler', 'schedule remove shuffle-leader-scheduler', 'schedule remove random-merge-scheduler' ] 
          }

### What did you expect?
no panic

### What did happened?
tikv panic at "state: Merging region"

{"container":"tikv","namespace":"ha-test-tikv-failure-rpt-tps-2700177-1-687","pod":"tc-tikv-0","log":"[[lib.rs:510](http://lib.rs:510/)] [\"state: Merging region { id: 228848 start_key: 7480000000000000FF6A5F720380000000FF0000113903800000FF0000000005038000FF000000000BC30380FF0000000000000E00FE end_key: 7480000000000000FF6A5F720380000000FF0000123103800000FF0000000006038000FF0000000002CE0380FF0000000000000300FE region_epoch { conf_ver: 35 version: 814 } peers { id: 228849 store_id: 1 } peers { id: 228850 store_id: 4 } peers { id: 228851 store_id: 5 } } merge_state { min_index: 124 target { id: 228852 start_key: 7480000000000000FF6A5F720380000000FF0000123103800000FF0000000006038000FF0000000002CE0380FF0000000000000300FE end_key: 7480000000000000FF6A5F720380000000FF0000141603800000FF0000000004038000FF0000000003160380FF0000000000000200FE region_epoch { conf_ver: 33 version: 813 } peers { id: 228853 store_id: 1 } peers { id: 228854 store_id: 4 } peers { id: 228855 store_id: 5 } } commit: 124 } tablet_index: 5\"] [backtrace=\"   0: tikv_util::set_panic_hook::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/lib.rs:509:18\\n](http://github.com/pingcap/tikv/components/tikv_util/src/lib.rs:509:18//n)   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\\n             at rust/toolchains/nightly-2023-08-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:2021](http://boxed.rs:2021/):9\\n      std::panicking::rust_panic_with_hook\\n             at rust/toolchains/nightly-2023-08-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:733](http://panicking.rs:733/):13\\n   2: std::panicking::begin_panic_handler::{{closure}}\\n             at rust/toolchains/nightly-2023-08-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:621](http://panicking.rs:621/):13\\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\\n             at rust/toolchains/nightly-2023-08-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/[backtrace.rs:170](http://backtrace.rs:170/):18\\n   4: rust_begin_unwind\\n             at rust/toolchains/nightly-2023-08-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:617](http://panicking.rs:617/):5\\n   5: core::panicking::panic_fmt\\n             at rust/toolchains/nightly-2023-08-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/[panicking.rs:67](http://panicking.rs:67/):14\\n   6: raftstore_v2::operation::command::admin::merge::prepare::<impl raftstore_v2::raft::apply::Apply<EK,R>>::apply_prepare_merge::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/admin/merge/prepare.rs:744:9\\n](http://github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/admin/merge/prepare.rs:744:9//n)      raftstore_v2::operation::command::<impl raftstore_v2::raft::apply::Apply<EK,R>>::apply_entry::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/mod.rs:728:68\\n](http://github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/mod.rs:728:68//n)   7: raftstore_v2::operation::command::<impl raftstore_v2::raft::apply::Apply<EK,R>>::apply_committed_entries::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/mod.rs:609:62\\n](http://github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/mod.rs:609:62//n)      raftstore_v2::fsm::apply::ApplyFsm<EK,R>::handle_all_tasks::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/fsm/apply.rs:148:95\\n](http://github.com/pingcap/tikv/components/raftstore-v2/src/fsm/apply.rs:148:95//n)   8: raftstore_v2::operation::command::<impl raftstore_v2::raft::peer::Peer<EK,ER>>::schedule_apply_fsm::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/mod.rs:163:62\\n](http://github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/mod.rs:163:62//n)      <tracker::tls::TrackedFuture<F> as core::future::future::Future>::poll::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tracker/src/tls.rs:64:23\\n](http://github.com/pingcap/tikv/components/tracker/src/tls.rs:64:23//n)      std::thread::local::LocalKey<T>::try_with\\n             at rust/toolchains/nightly-2023-08-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[local.rs:270](http://local.rs:270/):16\\n      std::thread::local::LocalKey<T>::with\\n             at rust/toolchains/nightly-2023-08-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[local.rs:246](http://local.rs:246/):9\\n      <tracker::tls::TrackedFuture<F> as core::future::future::Future>::poll\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tracker/src/tls.rs:62:27\\n](http://github.com/pingcap/tikv/components/tracker/src/tls.rs:62:27//n)      tikv_util::yatp_pool::future_pool::PoolInner::spawn::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/future_pool.rs:178:28\\n](http://github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/future_pool.rs:178:28//n)      yatp::task::future::RawTask<F>::poll\\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5572a78/src/task/[future.rs:59](http://future.rs:59/):9\\n   9: yatp::task::future::TaskCell::poll\\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5572a78/src/task/[future.rs:103](http://future.rs:103/):9\\n      <yatp::task::future::Runner as yatp::pool::runner::Runner>::handle\\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5572a78/src/task/[future.rs:387](http://future.rs:387/):20\\n  10: <tikv_util::yatp_pool::YatpPoolRunner<T> as yatp::pool::runner::Runner>::handle\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/mod.rs:196:24\\n](http://github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/mod.rs:196:24//n)      yatp::pool::worker::WorkerThread<T,R>::run\\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5572a78/src/pool/[worker.rs:48](http://worker.rs:48/):13\\n      yatp::pool::builder::LazyBuilder<T>::build::{{closure}}\\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5572a78/src/pool/[builder.rs:114](http://builder.rs:114/):25\\n      std::sys_common::backtrace::__rust_begin_short_backtrace\\n             at rust/toolchains/nightly-2023-08-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/[backtrace.rs:154](http://backtrace.rs:154/):18\\n  11: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\\n             at rust/toolchains/nightly-2023-08-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[mod.rs:529](http://mod.rs:529/):17\\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\\n             at rust/toolchains/nightly-2023-08-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/[unwind_safe.rs:271](http://unwind_safe.rs:271/):9\\n      std::panicking::try::do_call\\n             at rust/toolchains/nightly-2023-08-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:524](http://panicking.rs:524/):40\\n      std::panicking::try\\n             at rust/toolchains/nightly-2023-08-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:488](http://panicking.rs:488/):19\\n      std::panic::catch_unwind\\n             at rust/toolchains/nightly-2023-08-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panic.rs:142](http://panic.rs:142/):14\\n      std::thread::Builder::spawn_unchecked_::{{closure}}\\n             at rust/toolchains/nightly-2023-08-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[mod.rs:528](http://mod.rs:528/):30\\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\\n             at rust/toolchains/nightly-2023-08-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/[function.rs:250](http://function.rs:250/):5\\n  12: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at rust/toolchains/nightly-2023-08-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:2007](http://boxed.rs:2007/):9\\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at rust/toolchains/nightly-2023-08-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:2007](http://boxed.rs:2007/):9\\n      std::sys::unix::thread::Thread::new::thread_start\\n             at rust/toolchains/nightly-2023-08-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/[thread.rs:108](http://thread.rs:108/):17\\n  13: start_thread\\n  14: __clone3\\n\"] [location=/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/admin/merge/prepare.rs:744](http://github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/admin/merge/prepare.rs:744)] [thread_name=apply-0]","level":"FATAL"}

**Comment by overvenus** [comment] 2023-09-27 07:40
The issue is caused by the loss of the PrepareMerge state after restarting TiKV, and has been resolved by #15649.

**Closed by overvenus** 2023-09-27 07:40 UTC
Labels: type/bug, severity/critical, may-affects-5.3, may-affects-5.4, may-affects-6.1, may-affects-6.5, may-affects-7.1, affects-7.4
