### ISSUE TITLE
after two tikv restart， The “Max Resolved TS gap” display is unreasonable

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#10702] opened 2021-08-11 04:23 UTC
### What version of TiKV are you using?
Release Version:   5.1.0-alpha
Edition:           Community
Git Commit Hash:   d78394cb8dcc3e55a53d34378253a0888d26b438
Git Commit Branch: heads/refs/tags/v5.2.0
UTC Build Time:    2021-08-09 12:08:07
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release

### What operating system and CPU are you using?
k8s环境
2 tidb，3 pd，4 tikv
tikv：8G、4 cores

### Steps to reproduce
TiKVFailover001
1、通过br导入tpcc数据：/br restore full --pd "tc-pd.glh-pv2gn.svc:2379" --storage "s3://benchmark/tpcc-1000-new" --s3.endpoint "http://minio.pingcap.net:9000" --send-credentials-to-tikv=true
2、two TiKV OOM（known issue：https://github.com/tikv/tikv/issues/10694）

### What did you expect?
after tikv recover，The “Max Resolved TS gap” display normal

### What did happened?
The “Max Resolved TS gap” display is unreasonable
![Lark20210811-121608](https://user-images.githubusercontent.com/84712107/128969292-d46675ba-4fd7-43c4-84d3-7fa01cd17999.png)
![Lark20210811-121641](https://user-images.githubusercontent.com/84712107/128969297-1895a00a-28ca-49ca-815e-4e64086c8937.png)

**Comment by NingLin-P** [comment] 2022-01-07 03:22
This issue is likely caused by https://github.com/tikv/tikv/issues/11400, close it since https://github.com/tikv/tikv/pull/11352 had fixed it.

**Closed by NingLin-P** 2022-01-07 03:22 UTC
Labels: type/bug, severity/minor
