### ISSUE TITLE
more than one of tikv panic when injection pd leader timeoffset (ahead 5mins)

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#18055] opened 2024-12-25 07:29 UTC
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   8.5.0-alpha
Edition:           Community
Git Commit Hash:   678edbe8fa3404c2d9f703031ca621792bf61cb7
Git Commit Branch: HEAD
UTC Build Time:    2024-12-23 07:24:00
Rust Version:      rustc 1.77.0-nightly (89e2160c4 2023-12-27)
Enable Features:   memory-engine pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine trace-async-tasks openssl-vendored
Profile:           dist_release
2024-12-24T16:32:05.343+0800

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、run tpcc
2、inject pd leader timeoffset （ahead 5mins）

### What did you expect?
no panic

### What did happened?
more than one of tikv panic 

`[2024/12/24 20:48:29.849 +08:00] [FATAL] [lib.rs:480] ["invalid max_ts update: 454831586436448257 exceeds the limit 454831522761670656, source=prepare_snap_ctx-get-454831586436448257"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             at workspace/source/tikv/components/tikv_util/src/lib.rs:479:18\n   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2029:9\n      std::panicking::rust_panic_with_hook\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:783:13\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:657:13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:171:18\n   4: rust_begin_unwind\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:645:5\n   5: core::panicking::panic_fmt\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:72:14\n   6: concurrency_manager::ConcurrencyManager::report_error\n   7: concurrency_manager::ConcurrencyManager::update_max_ts\n      tikv::storage::prepare_snap_ctx\n             at workspace/source/tikv/src/storage/mod.rs:3358:9\n   8: tikv::storage::Storage<E,L,F>::get::{{closure}}\n             at workspace/source/tikv/src/storage/mod.rs:666:32\n      <resource_metering::InTags<T> as core::future::future::Future>::poll\n             at workspace/source/tikv/components/resource_metering/src/lib.rs:274:9\n      <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll\n             at workspace/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/futures-util-0.3.31/src/future/future/map.rs:55:37\n      <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll\n             at workspace/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/futures-util-0.3.31/src/lib.rs:86:13\n   9: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll\n             at workspace/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/futures-util-0.3.31/src/future/future/map.rs:55:37\n      <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll\n             at workspace/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/futures-util-0.3.31/src/lib.rs:86:13\n      <resource_control::future::ControlledFuture<F> as core::future::future::Future>::poll\n             at workspace/source/tikv/components/resource_control/src/future.rs:48:19\n  10: resource_control::future::with_resource_limiter::{{closure}}\n             at workspace/source/tikv/components/resource_control/src/future.rs:204:11\n      <tracker::tls::TrackedFuture<F> as core::future::future::Future>::poll::{{closure}}\n             at workspace/source/tikv/components/tracker/src/tls.rs:64:23\n      std::thread::local::LocalKey<T>::try_with\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:270:16\n      std::thread::local::LocalKey<T>::with\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:246:9\n      <tracker::tls::TrackedFuture<F> as core::future::future::Future>::poll\n             at workspace/source/tikv/components/tracker/src/tls.rs:62:27\n      yatp::task::future::RawTask<F>::poll\n             at workspace/.cargo/git/checkouts/yatp-e704b73c3ee279b6/793be4d/src/task/future.rs:59:9\n  11: yatp::task::future::TaskCell::poll\n             at workspace/.cargo/git/checkouts/yatp-e704b73c3ee279b6/793be4d/src/task/future.rs:103:9\n      <yatp::task::future::Runner as yatp::pool::runner::Runner>::handle\n             at workspace/.cargo/git/checkouts/yatp-e704b73c3ee279b6/793be4d/src/task/future.rs:387:20\n  12: <tikv_util::yatp_pool::YatpPoolRunner<T> as yatp::pool::runner::Runner>::handle\n             at workspace/source/tikv/components/tikv_util/src/yatp_pool/mod.rs:199:24\n      <yatp::queue::multilevel::TrackedRunner<R> as yatp::pool::runner::Runner>::handle\n             at workspace/.cargo/git/checkouts/yatp-e704b73c3ee279b6/793be4d/src/queue/multilevel.rs:285:19\n  13: yatp::pool::worker::WorkerThread<T,R>::run\n             at workspace/.cargo/git/checkouts/yatp-e704b73c3ee279b6/793be4d/src/pool/worker.rs:48:13\n      yatp::pool::builder::LazyBuilder<T>::build::{{closure}}\n             at workspace/.cargo/git/checkouts/yatp-e704b73c3ee279b6/793be4d/src/pool/builder.rs:114:25\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:155:18\n  14: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:529:17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9\n      std::panicking::try::do_call\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40\n      std::panicking::try\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:516:19\n      std::panic::catch_unwind\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:142:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:528:30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5\n  15: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9\n      std::sys::unix::thread::Thread::new::thread_start\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17\n  16: start_thread\n  17: __GI___clone\n"] [location=/workspace/source/tikv/components/concurrency_manager/src/lib.rs:224] [thread_name=unified-read-pool-5] [thread_id=37]`

**Comment by glorv** [comment] 2024-12-25 07:49
reassign to @ekexium  as it's a txn related issue.

**Comment by ekexium** [comment] 2024-12-25 07:54
It was caused by an intentional max_ts validity check https://github.com/tikv/tikv/pull/17917. The injected clock offset far exceeds the allowance config (by default 60s)

**Closed** 2024-12-27 08:37 UTC
Labels: type/bug, sig/transaction, severity/critical, impact/panic
