### ISSUE TITLE
checks for snapshot last index is wrong

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#12618] opened 2022-05-23 16:36 UTC
## Bug Report

https://github.com/tikv/tikv/blob/1fb8980ccab9ff40c1adc206df52952dab8e8ad8/components/raftstore/src/store/peer_storage.rs#L467-L475

Supposing a leader append a lot of logs without replicating any of them. After several elections, new leader compacts all previous logs. If the old leader rejoin the group, new leader will send it a snapshot. If old leader exits before updating raft state, then the condition will be false and result in corrupted state.

**Comment by LintianShi** [comment] 2022-07-16 12:46
The root cause of this bug is that both apply state and raft state are updated during snapshot applying. However, apply state and raft state are seperately persisted in kvdb and raftdb. So we cannot write apply state and raft state atomically. If the instance crashes during snapshot applying, raft state may not be persisted successfully while apply state is persisted. When the instance recovers from the snapshot-applying state, the raft state is possible to be inconsistent with apply state.  

The current solution is that we saves a copy of raft state into kvdb which is named `snapshot_raft_state`. When recovering from the snapshot-applying state, we check the `snapshot_raft_state` in kvdb with raft state in raftdb. If the last index of raft state is behind the snapshot_raft_state, we use `snapshot_raft_state` as the correct raft state. Unluckily, the above solution still has a corner case mentioned by Jay. 

To ensure the correctness of recovering, we can use `snapshot_raft_state` to recover the raft state in every situation. The drawback of this solution is that the log entries appended during snapshot applying may be dropped after recovery. However, appending log entries during snapshot applying occurs with low possibility. So this solution may not hurt the performance a lot.

**Comment by BusyJay** [comment] 2022-07-16 22:57
How about checking `commit` field instead?

**Comment by LintianShi** [comment] 2022-07-17 02:50
I find weird that `commit` field in RaftLocalState.hard_state is not updated in `fn apply_snapshot`. Is it expected?

**Comment by BusyJay** [comment] 2022-07-17 13:37
It should be updated in the end. You can verify it with a test case.

**Comment by LintianShi** [comment] 2022-07-18 08:07
Yes, `commit` is updated out of `fn apply_snapshot`. It is updated in `fn handle_raft_ready`.

**Comment by LintianShi** [comment] 2022-07-21 08:28
As the `commit` of raft state always increases monotonically, we can use `commit` to check snapshot raft state in kvdb with raft state in raftdb. 
In `save_snapshot_raft_state_to`, the commit of snapshot_raft_state is set to snapshot_index (snapshot_index is the applied index of the leader). Since the peer rejects snapshot whose snapshot_index is smaller than commit of its raft state, we ensure that the commit of raft state cannot decrease if snapshot is applied successfully. When recovering from applying snapshot state, we can confirm that raft_state failed to persist if commit in raft_state is smaller than that in snapshot_raft_state.
If snapshot_index is equal to the commit of the follower, it seems difficult to handle. However, the follower will only forward its apply state if it receives a snapshot with snapshot_index equal to its commit. It can be seen as the follower has applied all its committed log. If the raft state fails to persist, it does not affect correctness. We just keep those uncommitted log entries.

**Comment by LintianShi** [comment] 2022-07-21 08:28
PR: https://github.com/tikv/tikv/pull/13088

**Closed** 2022-08-29 05:18 UTC
Labels: type/bug, severity/major, affects-4.0, affects-5.0, affects-5.1, affects-5.2, affects-5.3, affects-5.4, affects-6.0, affects-6.1, affects-6.2
