### ISSUE TITLE
Build TiKV failed because 'google' has not been declared when compile rust-rocksdb

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#4049] opened 2019-01-10 06:55 UTC
## Bug Report

**What version of Rust are you using?**

rustc 1.29.0-nightly (4f3c7a472 2018-07-17)

**What operating system and CPU are you using?**
CentOS7 3.10.0-862.el7.x86_64

**What did you do?**

`make unportable_release`

**What did you expect to see?**

Build successfully.

**What did you see instead?**

```
gmake[5]: Leaving directory `/data3/tangliu/tikv/target/release/build/librocksdb_sys-209ad5b0b08f68be/out/build'
gmake[4]: Leaving directory `/data3/tangliu/tikv/target/release/build/librocksdb_sys-209ad5b0b08f68be/out/build'
gmake[3]: Leaving directory `/data3/tangliu/tikv/target/release/build/librocksdb_sys-209ad5b0b08f68be/out/build'
gmake[2]: Leaving directory `/data3/tangliu/tikv/target/release/build/librocksdb_sys-209ad5b0b08f68be/out/build'

--- stderr
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
In file included from /home/pingcap/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/2a65792/librocksdb_sys/rocksdb/tools/db_bench_tool.cc:65:0:
/home/pingcap/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/2a65792/librocksdb_sys/rocksdb/util/gflags_compat.h:11:26: error: 'google' has not been declared
 #define GFLAGS_NAMESPACE google
                          ^
/home/pingcap/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/2a65792/librocksdb_sys/rocksdb/tools/db_bench_tool.cc:82:7: note: in expansion of macro 'GFLAGS_NAMESPACE'
 using GFLAGS_NAMESPACE::ParseCommandLineFlags;
```

It is weird that building db_bench_tool for TiKV.

**Comment by DorianZheng** [comment] 2019-01-11 05:41
Thanks @siddontang for the issue. We won't build RocksDB with GFlags unless you have installed GFlags.  Could you find any GFlags library in `/usr/local/lib` or `/usr/lib`? If yes, which version of GFlags you are using?

**Comment by DorianZheng** [comment] 2019-01-17 03:09
I think this issue is caused by an old version of GFlags. I will close it, but feel free to re-open it if you there is anything else to do with this issue.

**Closed by DorianZheng** 2019-01-17 03:09 UTC
Labels: T: Bug
