### ISSUE TITLE
tikv panic：[region 12786953] 12786955 hash at 226 not correct, want \"\\200\\207\\326{\", got \"5\\305'R\"!!!"

### ISSUE THREAD

**Issue by vivid392845427** [tikv/tikv#12253] opened 2022-03-23 16:51 UTC
### What version of TiKV are you using?
```
[2022/03/20 15:12:04.141 +00:00] [INFO] [lib.rs:80] ["Welcome to TiKV"]
[2022/03/20 15:12:04.157 +00:00] [INFO] [lib.rs:85] ["Release Version:   6.0.0-alpha"]
[2022/03/20 15:12:04.157 +00:00] [INFO] [lib.rs:85] ["Edition:           Community"]
[2022/03/20 15:12:04.157 +00:00] [INFO] [lib.rs:85] ["Git Commit Hash:   18a119cbc551db53c1025912c164d994461f3aee"]
[2022/03/20 15:12:04.158 +00:00] [INFO] [lib.rs:85] ["Git Commit Branch: heads/refs/tags/v6.0.0-alpha"]
[2022/03/20 15:12:04.158 +00:00] [INFO] [lib.rs:85] ["UTC Build Time:    Unknown (env var does not exist when building)"]
[2022/03/20 15:12:04.158 +00:00] [INFO] [lib.rs:85] ["Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)"]
[2022/03/20 15:12:04.158 +00:00] [INFO] [lib.rs:85] ["Enable Features:   jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure"]
[2022/03/20 15:12:04.158 +00:00] [INFO] [lib.rs:85] ["Profile:           dist_release"]
[2022/03/20 15:12:04.158 +00:00] [INFO] [mod.rs:73] ["cgroup quota: memory=9223372036854771712, cpu=None, cores={3, 0, 7, 4, 1, 5, 6, 2}"]
[2022/03/20 15:12:04.158 +00:00] [INFO] [mod.rs:80] ["memory limit in bytes: 17056027648, cpu cores quota: 8"]
```

### What operating system and CPU are you using?
`do not care`

### Steps to reproduce
`set tikv configure："config-file": "[raftstore]\nconsistency-check-interval = \"60s\"\n";

run gc test in local, the case do follow step:
1、do dml operations continuous
2、do drop table/drop database continuous`

### What did you expect?
` tidb cluster is normal`

### What did happened?

tikv panic：
[2022/03/20 15:11:47.483 +00:00] [FATAL] [lib.rs:466] ["[region 12786953] 12786956 hash at 226 not correct, want \"\\200\\207\\326{\", got \"5\\305'R\"!!!"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:465:18\n   1: std::panicking::rust_panic_with_hook\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:702:17\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:588:13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:138:18\n   4: rust_begin_unwind\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:584:5\n   5: core::panicking::panic_fmt\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:143:14\n   6: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::verify_and_store_hash\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:4958:17\n   7: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_ready_verify_hash\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:4876:9\n      raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_ready_result\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:3970:22\n   8: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_apply_res\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:1566:17\n      raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::handle_msgs\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:648:21\n   9: <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_normal\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:789:9\n  10: batch_system::batch::Poller<N,C,Handler>::poll\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:446:27\n  11: raftstore::store::worker::refresh_config::PoolController<N,C,H>::increase_by::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/worker/refresh_config.rs:71:21\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:122:18\n  12: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/thread/mod.rs:498:17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panic/unwind_safe.rs:271:9\n      std::panicking::try::do_call\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:492:40\n      std::panicking::try\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:456:19\n      std::panic::catch_unwind\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panic.rs:137:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/thread/mod.rs:497:30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/ops/function.rs:227:5\n  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/boxed.rs:1854:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/boxed.rs:1854:9\n      std::sys::unix::thread::Thread::new::thread_start\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys/unix/thread.rs:108:17\n  14: start_thread\n  15: __clone\n"] [location=/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:4958] [thread_name=raftstore-5-0]

**Comment by you06** [comment] 2022-03-24 12:19
@BusyJay PTAL

**Comment by BusyJay** [comment] 2022-03-24 12:29
/cc @MyonKeminta PTAL.

I don't think consistency check still work after enabling compaction filter gc.

**Comment by MyonKeminta** [comment] 2022-03-25 06:34
As far as I know the consistency check was adapted to GC bypassing raft.
cc @hicqu

**Comment by BusyJay** [comment] 2022-03-25 08:05
Well, the stacktrace shows it panic inside raft.

**Comment by hicqu** [comment] 2022-03-28 04:19
I have checked the algorithm of mvcc-consistency-check. Seems it's incompatible with  `GcRunner::unsafe_destroy_range`. @MyonKeminta do you have any idea for this?

**Comment by hicqu** [comment] 2022-03-28 08:37
Here is a test case which shows `delete_ranges_cf` can cause a different `compute_hash` result even if the snapshot is taken before it:
```rust
    #[test]
    fn test_mvcc_checksum_with_delete_files_in_range() {
        use engine_rocks::raw::CompactOptions;
        use engine_rocks::util::get_cf_handle;
        use engine_traits::{DeleteStrategy,Range, MiscExt};

        let init_safe_point = 100;
        for i in 0..2 {
            let engine = TestEngineBuilder::new().build().unwrap();
            let raw = engine.get_rocksdb();
            let db = raw.as_inner();
            must_prewrite_put(&engine, b"zAAAAA", b"value", b"PRIMARY", init_safe_point);
            must_commit(&engine, b"zAAAAA", init_safe_point, init_safe_point + 1);

            let handle = get_cf_handle(db, CF_WRITE).unwrap();
            let mut compact_opts = CompactOptions::new();
            compact_opts.set_change_level(true);
            compact_opts.set_target_level(6);
            db.compact_range_cf_opt(handle, &compact_opts, None, None);

            let snap = raw.snapshot();
            if i == 1 {
                let range = Range::new(&[b'z'], &[b'z' + 1]);
                raw.delete_ranges_cf(CF_WRITE, DeleteStrategy::DeleteFiles, &[range])
                    .unwrap();
                std::thread::sleep(std::time::Duration::from_secs(1));
            }

            let mut scanner = MvccInfoScanner::new(
                |cf, opts| snap.iterator_cf_opt(cf, opts).map_err(|e| box_err!(e)),
                Some(b"zA"),
                Some(b"zB"),
                MvccChecksum::new(init_safe_point),
            ).unwrap();

            while scanner.next_item().unwrap().is_some() {}
            let digest = scanner.observer.digest;
            let hash = digest.finalize();
            println!("hash: {:?}", hash);
        }
    }
```

The output is:
```
running 1 test
hash: 3628551031
hash: 0
test storage::mvcc::consistency_check::tests::test_mvcc_checksum_with_delete_files_in_range ... ok
```

**Comment by MyonKeminta** [comment] 2022-03-28 10:32
If it's confirmed to be caused by unsafe_destroy_range, it should be actually a known issue, and it doesn't need to block releasing.

**Comment by tonyxuqqi** [comment] 2022-03-28 17:59
@vivid392845427 could you please disable the gc.enable-compaction-filter and run the test again?
If it cannot be repro-ed then we're pretty sure this is the known issue. 
@BusyJay Maybe we should skip the consistency check run when gc.enable-compaction-filter is enabled?

**Comment by 5kbpers** [comment] 2022-07-26 08:42
Added an alert to suggest no consistency check when enabling GC https://github.com/pingcap/docs-cn/pull/9526, close this issue until resolving this compatibility issue.

**Closed by 5kbpers** 2022-07-26 08:42 UTC
Labels: type/bug, severity/major, affects-6.0, affects-6.1, affects-6.2
