### ISSUE TITLE
Creating tons of tables make TiKV OOM

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#17199] opened 2024-06-26 08:44 UTC
### What version of TiKV are you using?

nightly

### What operating system and CPU are you using?

Not related 

### Steps to reproduce

Three TiKVs with 16G memory and create 300,000 empty tables

### What did you expect?
not OOM

### What did happened?
OOM

**Comment by overvenus** [comment] 2024-06-27 10:02
Duplicate of https://github.com/tikv/tikv/issues/16229

**Closed by overvenus** 2024-06-27 10:02 UTC
Labels: type/bug
