### ISSUE TITLE
TiKV nodes output FATAL log "[FATAL] [lib.rs:499] ["header name validated by httparse: InvalidHeaderName { _priv: () }"]"

### ISSUE THREAD

**Issue by superlzs0476** [tikv/tikv#8478] opened 2020-08-20 12:09 UTC
### Introduction

Meitu Taitan's client connects tikv to handle read and write requests. Today this tikv cluster is an abnormal restart, and the administrator didn't any operators before the incident. As tikv cluster auto-restart has completed now,  Meitu client and TiKV cluster working are normal, but they want to know what happened with this cluster.

### TiKV log of Fatal:
```log
[2020/08/20 19:13:23.707 +08:00] [FATAL] [lib.rs:499] ["header name validated by httparse: InvalidHeaderName { _priv: () }"] [backtrace="stack backtrace:\n   0:     0x555c521472dd - backtrace::backtrace::libunwind::trace::h0500f4f2825a5d17\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/libunwind.rs:54\n                         - backtrace::backtrace::trace::h4187244de1605a06\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/mod.rs:70\n   1:     0x555c5213b960 - tikv_util::set_panic_hook::{{closure}}::h74abe81d776d6325\n                        at /home/jenkins/.target/release/build/backtrace-e20a32a05fd0b8fe/out/capture.rs:79\n   2:     0x555c522e06af - std::panicking::rust_panic_with_hook::h8d2408723e9a2bd4\n                        at src/libstd/panicking.rs:479\n   3:     0x555c522e048d - std::panicking::continue_panic_fmt::hb2aaa9386c4e5e80\n                        at src/libstd/panicking.rs:382\n   4:     0x555c522efbf5 - rust_begin_unwind\n                        at src/libstd/panicking.rs:309\n   5:     0x555c522fa79b - core::panicking::panic_fmt::h79e840586f23493b\n                        at src/libcore/panicking.rs:85\n   6:     0x555c51f8d809 - core::result::unwrap_failed::h4023417ed3851a34\n                        at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libcore/macros.rs:18\n   7:     0x555c51f92637 - core::result::Result<T,E>::expect::h2d5bcb822090ae16\n                        at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libcore/result.rs:827\n                         - <hyper::proto::h1::role::Server as hyper::proto::h1::Http1Transaction>::parse::h40288ec718695a7d\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.18/src/proto/h1/role.rs:141\n   8:     0x555c5168bf32 - hyper::proto::h1::io::Buffered<T,B>::parse::h40db12ea05dd7c60\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.18/src/proto/h1/io.rs:144\n                         - hyper::proto::h1::conn::Conn<I,B,T>::read_head::h2d88b054a603f536\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.18/src/proto/h1/conn.rs:137\n                         - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_read_head::h98be40a09d4790c2\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.18/src/proto/h1/dispatch.rs:200\n                         - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_read::hcc1674370b39d804\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.18/src/proto/h1/dispatch.rs:136\n   9:     0x555c5168298f - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner::h94d0c90f83e7baf1\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.18/src/proto/h1/dispatch.rs:100\n                         - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch::h3b714443aecaa23c\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.18/src/proto/h1/dispatch.rs:86\n                         - <hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T> as futures::future::Future>::poll::h77451491e9e8ae97\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.18/src/proto/h1/dispatch.rs:348\n                         - <futures::future::either::Either<A,B> as futures::future::Future>::poll::hc62ca60ec79b8d65\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.23/src/future/either.rs:35\n                         - futures::future::option::<impl futures::future::Future for core::option::Option<F>>::poll::hb79588b571f200b9\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.23/src/future/option.rs:12\n                         - <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as futures::future::Future>::poll::hd5abb740ce5b64f6\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.18/src/server/conn.rs:880\n  10:     0x555c5167e9f8 - <hyper::common::drain::Watching<F,FN> as futures::future::Future>::poll::h427d6bcf7b7dd3c9\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.18/src/common/drain.rs:0\n                         - <hyper::server::conn::spawn_all::NewSvcTask<I,N,S,E,W> as futures::future::Future>::poll::hfb6fe8f18183d1a0\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.18/src/server/conn.rs:820\n  11:     0x555c521a7b9f - <alloc::boxed::Box<F> as futures::future::Future>::poll::h8cbc17c2ae628587\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.23/src/future/mod.rs:113\n                         - futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}::he0e06af936a7db5b\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.23/src/task_impl/mod.rs:289\n                         - futures::task_impl::Spawn<T>::enter::{{closure}}::hff9e10e7a1c54b08\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.23/src/task_impl/mod.rs:363\n                         - futures::task_impl::std::set::h7c061ecd86b3288a\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.23/src/task_impl/std/mod.rs:78\n                         - futures::task_impl::Spawn<T>::enter::h7f6739b8ee3813df\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.23/src/task_impl/mod.rs:363\n                         - futures::task_impl::Spawn<T>::poll_future_notify::hfd2b1d24b82d08c0\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.23/src/task_impl/mod.rs:289\n                         - tokio_threadpool::task::Task::run::{{closure}}::h43eb350562ac60cc\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/task/mod.rs:145\n                         - core::ops::function::FnOnce::call_once::h7ce9b55ef3fa6c1a\n                        at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libcore/ops/function.rs:231\n                         - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h2aebb1347bc3c977\n                        at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/panic.rs:309\n                         - std::panicking::try::do_call::h10d6e31cf2732b8b\n                        at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/panicking.rs:294\n                         - std::panicking::try::h3abc33e0188db72f\n                        at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250//src/libpanic_abort/lib.rs:29\n                         - std::panic::catch_unwind::hf571382cd39c1685\n                        at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/panic.rs:388\n                         - tokio_threadpool::task::Task::run::he125053cb58ebf6e\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/task/mod.rs:130\n                         - tokio_threadpool::worker::Worker::run_task2::hf94d4bad3d4698af\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:567\n                         - tokio_threadpool::worker::Worker::run_task::hfd068088fa11c147\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:459\n  12:     0x555c521a51bc - tokio_threadpool::worker::Worker::try_run_owned_task::h5f944978647c54e7\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:390\n                         - tokio_threadpool::worker::Worker::try_run_task::hef8b195dfeb261cc\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:297\n                         - tokio_threadpool::worker::Worker::run::h156a98859dab53e6\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:241\n  13:     0x555c521a4a67 - tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}::h625953cf83a49aee\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:129\n                         - tokio_executor::global::with_default::{{closure}}::h6044fc3c41017351\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.7/src/global.rs:209\n                         - std::thread::local::LocalKey<T>::try_with::h6067f298551972ff\n                        at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/thread/local.rs:299\n                         - std::thread::local::LocalKey<T>::with::h5db46eed449e8bfb\n                        at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/thread/local.rs:245\n                         - tokio_executor::global::with_default::h31499108732def82\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.7/src/global.rs:178\n                         - tokio_threadpool::worker::Worker::do_run::{{closure}}::had30c83e581f766a\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:125\n                         - std::thread::local::LocalKey<T>::try_with::h08d668158cde9e24\n                        at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/thread/local.rs:299\n                         - std::thread::local::LocalKey<T>::with::h873fd50960a9c49a\n                        at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/thread/local.rs:245\n                         - tokio_threadpool::worker::Worker::do_run::h269294a47412c6f8\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:116\n                         - tokio_threadpool::pool::Pool::spawn_thread::{{closure}}::hfe390b1c8f41d2c8\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/pool/mod.rs:344\n                         - std::sys_common::backtrace::__rust_begin_short_backtrace::h7bc7b49b4e68827c\n                        at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/sys_common/backtrace.rs:77\n  14:     0x555c521a4748 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hb91b17123de840cc\n                        at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/thread/mod.rs:470\n                         - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h20a7800d7aac507f\n                        at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/panic.rs:309\n                         - std::panicking::try::do_call::h5ad8e465f088e869\n                        at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/panicking.rs:294\n                         - std::panicking::try::h9173cde0eb56789d\n                        at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250//src/libpanic_abort/lib.rs:29\n                         - std::panic::catch_unwind::hbb14089b36838a89\n                        at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/panic.rs:388\n                         - std::thread::Builder::spawn_unchecked::{{closure}}::hc48260744173abd6\n                        at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libstd/thread/mod.rs:469\n                         - core::ops::function::FnOnce::call_once{{vtable.shim}}::h8f9bdd71e836dfcb\n                        at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/libcore/ops/function.rs:231\n  15:     0x555c522eebfe - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::he71721d2d956d451\n                        at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/liballoc/boxed.rs:746\n  16:     0x555c522f0f2b - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::he520045b8d28ce5c\n                        at /rustc/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/liballoc/boxed.rs:746\n                         - std::sys_common::thread::start_thread::h2e98d1272dc6d74b\n                        at src/libstd/sys_common/thread.rs:13\n                         - std::sys::unix::thread::Thread::new::thread_start::h18485805666ccd3c\n                        at src/libstd/sys/unix/thread.rs:79\n  17:     0x7fe707aabe24 - start_thread\n  18:     0x7fe7071b734c - __clone\n  19:                0x0 - <unknown>"] [location=src/libcore/result.rs:999] [thread_name=status-server-0]
[2020/08/20 19:13:28.337 +08:00] [INFO] [mod.rs:26] ["Welcome to TiKV."]
[2020/08/20 19:13:28.338 +08:00] [INFO] [mod.rs:28] []
[2020/08/20 19:13:28.338 +08:00] [INFO] [mod.rs:28] ["Release Version:   3.0.4"]
[2020/08/20 19:13:28.338 +08:00] [INFO] [mod.rs:28] ["Git Commit Hash:   6bdb5c093a18437ee28b1216a2415eda4f2ba8c7"]
[2020/08/20 19:13:28.338 +08:00] [INFO] [mod.rs:28] ["Git Commit Branch: HEAD"]
[2020/08/20 19:13:28.338 +08:00] [INFO] [mod.rs:28] ["UTC Build Time:    2019-10-08 08:11:11"]
[2020/08/20 19:13:28.338 +08:00] [INFO] [mod.rs:28] ["Rust Version:      rustc 1.37.0-nightly (0e4a56b4b 2019-06-13)"]
[2020/08/20 19:13:28.338 +08:00] [INFO] [mod.rs:30] []
```

**Comment by BusyJay** [comment] 2020-08-20 12:48
Should be caused by hyperium/hyper#1587.

**Comment by BusyJay** [comment] 2020-08-20 12:50
It was fixed in 4.0.

**Comment by superlzs0476** [comment] 2020-08-20 12:57
Should we merge it in v3.0 ？

**Comment by BusyJay** [comment] 2020-08-20 13:43
Sure. A simple `cargo update -p httparse` should fix the problem on release-3.0 branch.

**Comment by piaoairy219** [comment] 2020-08-24 01:45
ok, we will update it to 4.0 today:)

**Comment by youjiali1995** [comment] 2020-09-24 07:44
fixed by https://github.com/tikv/tikv/pull/8540

**Closed by youjiali1995** 2020-09-24 07:44 UTC
Labels: difficulty/easy, priority/low, severity/Major, status/help-wanted, type/bug
