### ISSUE TITLE
TiKV panicked due to corrupted meta

### ISSUE THREAD

**Issue by zyguan** [tikv/tikv#13311] opened 2022-08-19 01:30 UTC
### What version of TiKV are you using?

master

### What operating system and CPU are you using?

kubernetes

### Steps to reproduce

run jepsen with the following options
```edn
{:auto-retry-limit :default,
 :ssh-private-key "jepsen.pem",
 :isolation :repeatable-read,
 :concurrency 15,
 :predicate-read false,
 :tarball-url
 "http://minio.pingcap.net:9000/tp-team/tests/jepsen/tidb-master-linux-amd64.tar.gz",
 :txn-mode "optimistic",
 :force-reinstall true,
 :update-in-place false,
 :ssh
 {:username "root",
  :password "root",
  :strict-host-key-checking false,
  :private-key-path "jepsen.pem"},
 :nemesis-long-recovery false,
 :follower-read true,
 :nemesis
 {:interval 10,
  :schedules true,
  :partition-pd-leader true,
  :partition-half true,
  :partition-ring true},
 :nodes
 ["node-0.node-peer.jepsen-tps-1170516-1-921"
  "node-1.node-peer.jepsen-tps-1170516-1-921"
  "node-2.node-peer.jepsen-tps-1170516-1-921"
  "node-3.node-peer.jepsen-tps-1170516-1-921"
  "node-4.node-peer.jepsen-tps-1170516-1-921"],
 :test-count 1,
 :read-lock nil,
 :use-index false,
 :table-cache false,
 :os #object[tidb.core.Image 0x604d28c6 "tidb.core.Image@604d28c6"],
 :time-limit 600,
 :recovery-time 10,
 :version "master",
 :auto-retry :default,
 :workload :bank-multitable,
 :init-txn-sql
 ("set @@tidb_enable_async_commit = 0, @@tidb_enable_1pc = 0"
  "set @@tidb_enable_async_commit = 1, @@tidb_enable_1pc = 0"
  "set @@tidb_enable_async_commit = 1, @@tidb_enable_1pc = 1"),
 :init-sql
 ("set @@tidb_enable_mutation_checker=1, @@tidb_txn_assertion_level=strict")}
```

### What did you expect?

The test passed.

### What did happened?

TiKV panicked. ([full logs](http://minio.pingcap.net:9000/test-infra/2022-08-15/plan-exec-1170516/plan-exec-1170516-359813707/archive.tgz))
```
[2022/08/15 19:53:49.673 +00:00] [FATAL] [lib.rs:494] ["meta corrupted: no region for 3312 7A6D44423A32000000FF00FB000000000000FF00685461626C653AFF3638FF0000000000FF000000F700000000FB when creating 3307 region_id: 3307 from_peer { id: 3309 store_id: 1 } to_peer { id: 3558 store_id: 6 role: Learner } message { msg_type: MsgHeartbeat to: 3558 from: 3309 term: 7 } region_epoch { conf_ver: 152 version: 196 } start_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3600FE0000000000FA end_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3634FF0000000000FF000000F700000000FB"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:493:18\n   1: std::panicking::rust_panic_with_hook\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:702:17\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:588:13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:138:18\n   4: rust_begin_unwind\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:584:5\n   5: core::panicking::panic_fmt\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:142:14\n   6: raftstore::store::fsm::store::StoreFsmDelegate<EK,ER,T>::maybe_create_peer_internal\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:2081:25\n      raftstore::store::fsm::store::StoreFsmDelegate<EK,ER,T>::maybe_create_peer\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:2006:19\n   7: raftstore::store::fsm::store::StoreFsmDelegate<EK,ER,T>::on_raft_message\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:1936:20\n      raftstore::store::fsm::store::StoreFsmDelegate<EK,ER,T>::handle_msgs\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:709:37\n   8: <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_control\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:858:9\n      batch_system::batch::Poller<N,C,Handler>::poll\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:419:27\n   9: raftstore::store::worker::refresh_config::PoolController<N,C,H>::increase_by::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/worker/refresh_config.rs:78:21\n      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:415:23\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:122:18\n  10: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:505:17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:271:9\n      std::panicking::try::do_call\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:492:40\n      std::panicking::try\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:456:19\n      std::panic::catch_unwind\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:504:30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:248:5\n  11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1935:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1935:9\n      std::sys::unix::thread::Thread::new::thread_start\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17\n  12: start_thread\n  13: clone\n"] [location=/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:2081] [thread_name=raftstore-6-1]
   0: tikv_util::set_panic_hook::{{closure}}
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:493:18
   1: std::panicking::rust_panic_with_hook
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:588:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:142:14
   6: raftstore::store::fsm::store::StoreFsmDelegate<EK,ER,T>::maybe_create_peer_internal
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:2081:25
      raftstore::store::fsm::store::StoreFsmDelegate<EK,ER,T>::maybe_create_peer
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:2006:19
   7: raftstore::store::fsm::store::StoreFsmDelegate<EK,ER,T>::on_raft_message
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:1936:20
      raftstore::store::fsm::store::StoreFsmDelegate<EK,ER,T>::handle_msgs
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:709:37
   8: <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_control
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:858:9
      batch_system::batch::Poller<N,C,Handler>::poll
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:419:27
   9: raftstore::store::worker::refresh_config::PoolController<N,C,H>::increase_by::{{closure}}
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/worker/refresh_config.rs:78:21
      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:415:23
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:122:18
  10: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:505:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:504:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:248:5
  11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1935:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1935:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17
  12: start_thread
  13: clone
```

**Comment by cfzjywxk** [comment] 2022-08-20 01:32
The https://github.com/tikv/tikv/issues/12664 is reproduced in the Jepsen test environment.

```
[FATAL] [lib.rs:494] ["meta corrupted: no region for 3312 
7A6D44423A32000000FF00FB000000000000FF00685461626C653A
FF3638FF0000000000FF000000F700000000FB 
when creating 3307 region_id: 3307 from_peer { id: 3309 store_id: 1 } 
to_peer { id: 3558 store_id: 6 role: Learner } 
message { msg_type: MsgHeartbeat to: 3558 from: 3309 term: 7 } 
region_epoch { conf_ver: 152 version: 196 } 
start_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3600FE0000000000FA 
end_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3634FF0000000000FF000000F700000000FB"] 
```
The corresponding region(id=3312) information could not be found from `meta.regions`, when the replicated peer(peer_id=3558, region_id=3307) is created on node-4 and the overlapping check is executed.

---

From the logs in node-4, the peer of region(id=3312) is follows:
### 1. An uninitialized peer is created by replication.
./node-4.node-peer.jepsen-tps-1170516-1-921/kv.log:[2022/08/15 19:53:48.039 +00:00] [INFO] [peer.rs:305] ["replicate peer"] [**peer_id=3316**] [**region_id=3312**]
./node-4.node-peer.jepsen-tps-1170516-1-921/kv.log:[2022/08/15 19:53:48.039 +00:00] [INFO] [raft.rs:2646] ["switched to configuration"] [config="Configuration { voters: Configuration { incoming: Configuration { voters: {} }, outgoing: Configuration { voters: {} } }, learners: {}, learners_next: {}, auto_leave: false }"] [raft_id=3316] [region_id=3312]
./node-4.node-peer.jepsen-tps-1170516-1-921/kv.log:[2022/08/15 19:53:48.039 +00:00] [INFO] [raft.rs:1120] ["became follower at term 0"] [term=0] [raft_id=3316] [region_id=3312]
**./node-4.node-peer.jepsen-tps-1170516-1-921/kv.log:[2022/08/15 19:53:48.039 +00:00] [INFO] [raft.rs:384] [newRaft] [peers="Configuration { incoming: Configuration { voters: {} }, outgoing: Configuration { voters: {} } }"] ["last term"=0] ["last index"=0] [applied=0] [commit=0] [term=0] [raft_id=3316] [region_id=3312]**
./node-4.node-peer.jepsen-tps-1170516-1-921/kv.log:[2022/08/15 19:53:48.039 +00:00] [INFO] [raw_node.rs:315] ["RawNode created with id 3316."] [id=3316] [raft_id=3316] [region_id=3312]
./node-4.node-peer.jepsen-tps-1170516-1-921/kv.log:[2022/08/15 19:53:48.040 +00:00] [INFO] [raft.rs:1364] ["received a message with higher term from 3313"] ["msg type"=MsgHeartbeat] [message_term=6] [term=0] [from=3313] [raft_id=3316] [region_id=3312]

### 2. Region split is applied and handled.
./node-4.node-peer.jepsen-tps-1170516-1-921/kv.log:[2022/08/15 19:53:49.255 +00:00] [INFO] [apply.rs:1467] ["execute admin command"] [command="cmd_type: BatchSplit splits { requests { split_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3338FF0000000000FF000000F700000000FB new_region_id: 3282 new_peer_ids: 3283 new_peer_ids: 3284 new_peer_ids: 3285 new_peer_ids: 3286 } requests { split_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3432FF0000000000FF000000F700000000FB new_region_id: 3287 new_peer_ids: 3288 new_peer_ids: 3289 new_peer_ids: 3290 new_peer_ids: 3291 } requests { split_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3438FF0000000000FF000000F700000000FB new_region_id: 3292 new_peer_ids: 3293 new_peer_ids: 3294 new_peer_ids: 3295 new_peer_ids: 3296 } requests { split_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3534FF0000000000FF000000F700000000FB new_region_id: 3297 new_peer_ids: 3298 new_peer_ids: 3299 new_peer_ids: 3300 new_peer_ids: 3301 } requests { split_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3600FE0000000000FA new_region_id: 3302 new_peer_ids: 3303 new_peer_ids: 3304 new_peer_ids: 3305 new_peer_ids: 3306 } requests { split_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3634FF0000000000FF000000F700000000FB new_region_id: 3307 new_peer_ids: 3308 new_peer_ids: 3309 new_peer_ids: 3310 new_peer_ids: 3311 } requests { split_key: 6D44423A32000000FF00FB000000000000FF00685461626C653AFF3638FF0000000000FF000000F700000000FB new_region_id: 3312 new_peer_ids: 3313 new_peer_ids: 3314 new_peer_ids: 3315 new_peer_ids: 3316 } requests { split_key: 6D44423A32000000FF00FB000000000000FF00685461626C653AFF3734FF0000000000FF000000F700000000FB new_region_id: 3317 new_peer_ids: 3318 new_peer_ids: 3319 new_peer_ids: 3320 new_peer_ids: 3321 } requests { split_key: 6D44423A32000000FF00FB000000000000FF00685461626C653AFF3830FF0000000000FF000000F700000000FB new_region_id: 3322 new_peer_ids: 3323 new_peer_ids: 3324 new_peer_ids: 3325 new_peer_ids: 3326 } requests { split_key: 6D44427300000000FF00FA000000000000FF006844423A310000FF0000FB0000000000FA new_region_id: 3327 new_peer_ids: 3328 new_peer_ids: 3329 new_peer_ids: 3330 new_peer_ids: 3331 } right_derive: true }"] [index=278] [term=6] [peer_id=3204] [region_id=2090]
./node-4.node-peer.jepsen-tps-1170516-1-921/kv.log:[2022/08/15 19:53:49.258 +00:00] [INFO] [peer.rs:3711] [**"insert new region"**] [region="id: 3312 start_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3634FF0000000000FF000000F700000000FB end_key: 6D44423A32000000FF00FB000000000000FF00685461626C653AFF3638FF0000000000FF000000F700000000FB region_epoch { conf_ver: 150 version: 196 } peers { id: 3313 store_id: 7 } peers { id: 3314 store_id: 1 } peers { id: 3315 store_id: 5 } peers { id: 3316 store_id: 6 role: Learner }"] [region_id=3312]
./node-4.node-peer.jepsen-tps-1170516-1-921/kv.log:[2022/08/15 19:53:49.258 +00:00] [INFO] [router.rs:316] ["[region 3312] shutdown mailbox"]
./node-4.node-peer.jepsen-tps-1170516-1-921/kv.log:[2022/08/15 19:53:49.258 +00:00] [INFO] [peer.rs:255] ["create peer"] [peer_id=3316] [region_id=3312]
./node-4.node-peer.jepsen-tps-1170516-1-921/kv.log:[2022/08/15 19:53:49.258 +00:00] [INFO] [raft.rs:2646] ["switched to configuration"] [config="Configuration { voters: Configuration { incoming: Configuration { voters: {3313, 3314, 3315} }, outgoing: Configuration { voters: {} } }, learners: {3316}, learners_next: {}, auto_leave: false }"] [raft_id=3316] [region_id=3312]
./node-4.node-peer.jepsen-tps-1170516-1-921/kv.log:[2022/08/15 19:53:49.258 +00:00] [INFO] [raft.rs:1120] ["became follower at term 5"] [term=5] [raft_id=3316] [region_id=3312]
./node-4.node-peer.jepsen-tps-1170516-1-921/kv.log:[2022/08/15 19:53:49.258 +00:00] [INFO] [raft.rs:384] [newRaft] [peers="Configuration { incoming: Configuration { voters: {3313, 3314, 3315} }, outgoing: Configuration { voters: {} } }"] ["last term"=5] ["last index"=5] [applied=5] [commit=5] [term=5] [raft_id=3316] [region_id=3312]
./node-4.node-peer.jepsen-tps-1170516-1-921/kv.log:[2022/08/15 19:53:49.258 +00:00] [INFO] [raw_node.rs:315] ["RawNode created with id 3316."] [id=3316] [raft_id=3316] [region_id=3312]

### 3. Peer is destroyed because larger peer id is detected. Here the `meta.regions` and `meta.region_ranges` become inconsistent possibly.
./node-4.node-peer.jepsen-tps-1170516-1-921/kv.log:**[2022/08/15 19:53:49.261 +00:00] [INFO] [peer.rs:2604] ["target peer id is larger, destroying self"] [target_peer="id: 3535 store_id: 6 role: Learner"] [**peer_id=3316**] [region_id=3312]**
./node-4.node-peer.jepsen-tps-1170516-1-921/kv.log:[2022/08/15 19:53:49.261 +00:00] [INFO] [peer.rs:3280] ["starts destroy"] [merged_by_target=false] [peer_id=3316] [region_id=3312]
./node-4.node-peer.jepsen-tps-1170516-1-921/kv.log:[2022/08/15 19:53:49.261 +00:00] [INFO] [peer.rs:1255] ["begin to destroy"] [peer_id=3316] [region_id=3312]
./node-4.node-peer.jepsen-tps-1170516-1-921/kv.log:[2022/08/15 19:53:49.261 +00:00] [INFO] [peer.rs:1359] ["peer destroy itself"] [keep_data=false] [clean=false] [takes=2.6µs] [peer_id=3316] [region_id=3312]
./node-4.node-peer.jepsen-tps-1170516-1-921/kv.log:[2022/08/15 19:53:49.261 +00:00] [INFO] [router.rs:316] ["[region 3312] shutdown mailbox"]

### 4. Replication peer creating and overlap checking fails because information about region_id=3312 could not be found but it exists in the region ranges.
["meta corrupted: no region for 3312 7A6D44423A32000000FF00FB000000000000FF00685461626C653AFF3638FF0000000000FF000000F700000000FB when creating 3307 region_id: 3307 from_peer { id: 3309 store_id: 1 } to_peer { id: 3558 store_id: 6 role: Learner } message { msg_type: MsgHeartbeat to: 3558 from: 3309 term: 7 } region_epoch { conf_ver: 152 version: 196 } start_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3600FE0000000000FA end_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3634FF0000000000FF000000F700000000FB"]

---

It seems the destruction of a learner peer leads to the inconsistency between `meta.regions` and `meta.region_ranges`, but in step 3 the peer(id=3316) is already initialized so the destruction of the peer(id=3316) should have cleaned its information in `meta.regions_ranges` too, which could explain how the inconsistency happens directly, we still need to find a minimal reproduce step.

/cc @BusyJay @5kbpers

**Comment by BusyJay** [comment] 2022-10-08 05:23
I think the problem is due to the race between (1) replicating peer that has small ID, (2) split and (3) replicating peer that has larger ID. During being destroyed, (1) was confused and thought it was destroyed by (2). But actually it was destroyed by (3).

raftstore-v2 will not have the problem. This is another example to show how system can be error-prone without sequential lifetime control.

**Comment by cfzjywxk** [comment] 2022-10-10 03:57
I guess the flow is like this but I've not written a test case yet:
1. A replicating peer is created, for example, the `3316` here, it's uninitialized.
2. The `split apply result message` and `raft message with a larger peer id` are routed to the `3316` peer in a single store loop.
3. The split apply result processing creates an initialized peerFsm, note here that the `region_ranges` in `meta` is inserted with the new information.
4. The raft message whose target peer is larger is processed, the `peerFsm` which is uninitialized is still used and tries to destroy itself. As it's uninitialized the information in `region_ranges` is not cleared but the information in `regions` is cleared, thus inconsistency happens.

**Comment by cfzjywxk** [comment] 2023-07-06 06:35
Another reproduce in the jepsen test environemnt, the panic stack
```
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2032:9
      std::panicking::rust_panic_with_hook
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:692:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:579:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137:18
   4: rust_begin_unwind
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:575:5
   5: core::panicking::panic_fmt
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:65:14
   6: core::panicking::panic_display
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:138:5
   7: core::panicking::panic_str
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:122:5
   8: core::option::expect_failed
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1879:5
   9: core::option::Option<T>::expect
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:741:21
      <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/collections/hash/map.rs:1340:9
      raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::collect_sibling_region
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:5410:26
  10: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::pre_propose_raft_command
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:5251:17
  11: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::propose_raft_command_internal
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:5333:15
  12: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::propose_raft_command
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:5307:9
  13: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::handle_msgs
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:658:25
  14: <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_normal
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:999:9
  15: batch_system::batch::Poller<N,C,Handler>::poll
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:380:27
  16: batch_system::batch::BatchSystem<N,C>::start_poller::{{closure}}
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:550:17
      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:438:13
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rust/toolch
```

**Comment by zyguan** [comment] 2023-08-17 14:10
another two failures:
- [register-pessimistic-index-neterr](http://10.2.12.58:31714/workflows/testground/plan-exec-1920915-re0?tab=workflow&nodeId=plan-exec-1920915-re0-1598057878&nodePanelView=inputs-outputs)
- [append-mixed-syserr](http://10.2.12.58:31714/workflows/testground/plan-exec-1892325-re0?nodeId=plan-exec-1892325-re0-37395311)

**Closed** 2023-08-25 07:29 UTC
Labels: type/bug, severity/major, affects-6.5, affects-7.1
